'use client';

import { Input } from '@/components/ui/input';
import { frequencyLabel,shiftDate,type Schedule } from '@/lib/hotel-planning';
import type { HotelTables } from '@/lib/hotel-types';
import { currency } from '@/lib/hotel-view';
import { ActionButton as Button } from '@/modules/access/context';
import { Choice,download,Field,Form,History,MonthCalendar,Props,Text,weekdays } from '@/modules/shared/planning-ui';
import { useState } from 'react';
export function SupplierFields({supplier}:{supplier?:HotelTables['suppliers']}){
 const [frequency,setFrequency]=useState(supplier?.frequency??'Sin frecuencia'),s=supplier?JSON.parse(supplier.schedule) as Schedule:{start:'',end:'',weekdays:[],interval:null,dates:[]};
 return <><Field label="Nombre de proveedor" name="name" value={supplier?.name}/><Field label="Contacto" name="contact" value={supplier?.contact} required={false}/><Choice label="Rubros (selección múltiple)" name="rubros" value={supplier?JSON.parse(supplier.rubros):[]} multiple options={['Bebidas','Alimentos','Limpieza','Amenities','Reutilizables','Servicios','Otros']}/><Choice label="Frecuencia habitual" name="frequency" value={frequency} onChange={setFrequency} options={['Sin frecuencia','Semanal','Cada N días','Fechas puntuales']}/><Field label="Inicio / fecha de referencia" name="start" type="date" value={s.start} required={frequency==='Cada N días'}/><Field label="Fin de frecuencia (opcional)" name="end" type="date" value={s.end} required={false}/>{frequency==='Semanal'&&<Choice label="Días habituales (selección múltiple)" name="weekdays" multiple value={s.weekdays.map(String)} options={weekdays.map((w,i)=>[String(i),w])}/>}<Field label="Cada cuántos días (para intervalo)" name="interval" type="number" value={s.interval??''} required={frequency==='Cada N días'}/>{frequency==='Fechas puntuales'&&<Text label="Fechas puntuales: AAAA-MM-DD, una por línea" name="dates" value={s.dates.join('\n')} required/>}<Field label="Pedir cuántos días antes (opcional)" name="leadDays" type="number" value={supplier?.lead_days??''} required={false}/><Text label="Observaciones" name="observation" value={supplier?.observation}/><p className="form-note">La frecuencia genera entregas previstas, sin confirmarlas. Si no se conoce la fecha o el límite del pedido, queda A confirmar.</p></>;
}
export function SupplierAgenda({data,date,onSave,onPurchase}:Props & {onPurchase:(id:string)=>void}){
 const [filter,setFilter]=useState('Todos'),[state,setState]=useState('Todos'),[from,setFrom]=useState(date),[to,setTo]=useState(shiftDate(date,30)),[selected,setSelected]=useState(''),[edit,setEdit]=useState<{action:string;id?:string;supplier?:string}|null>(null);
 const supplier=data.suppliers.find(s=>s.id===(edit?.supplier??edit?.id)),delivery=data.supplier_deliveries.find(d=>d.id===edit?.id);
 const entities=data.suppliers.filter(s=>filter==='Todos'||s.id===filter);
 const events=data.supplier_deliveries.filter(e=>(filter==='Todos'||e.supplier===filter)&&(state==='Todos'||e.status===state));
 const listed=events.filter(e=>!e.date||e.date>=from&&e.date<=to).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||a.id.localeCompare(b.id));
 const exportList=()=>download('entregas-'+date,[['Proveedor','Contacto','Fecha prevista','Fecha original','Límite de pedido','Estado','Compra vinculada','Observaciones','Responsable'],...listed.map(e=>{const s=data.suppliers.find(s=>s.id===e.supplier)!;return [s.name,s.contact,e.date??'A confirmar',e.original_date??'A confirmar',e.deadline??'A confirmar',e.status,data.expenses.find(x=>x.id===e.expense)?.label??'',e.observation,e.responsible];})]);
 async function submit(v:Record<string,FormDataEntryValue>,fd:FormData){
  if(!edit)return;
  if(edit.action==='supplierProfile')await onSave(edit.action,{...v,id:supplier?.id??'',version:supplier?.version??0,rubros:fd.getAll('rubros'),leadDays:v.leadDays===''?null:Number(v.leadDays),schedule:{start:v.start||'',end:v.end||'',weekdays:fd.getAll('weekdays').map(Number),interval:v.interval?Number(v.interval):null,dates:String(v.dates??'').split(/[\s,;]+/).filter(Boolean)}});
  else if(edit.action==='deliveryGenerate')await onSave(edit.action,{...v,supplier:supplier!.id,version:supplier!.version});
  else await onSave(edit.action,{...v,id:delivery?.id??'',version:delivery?.version??0});
 }
 return <section className="panel planning-panel"><div className="panel-heading"><div><h2>Agenda de proveedores</h2><p>Visitas previstas y confirmadas, sin movimientos automáticos de stock ni caja.</p></div><div className="meal-row-actions"><Button onClick={()=>setEdit({action:'supplierProfile'})} permission="suppliers.create">Nuevo proveedor</Button><Button variant="outline" permission="suppliers.create" onClick={()=>setEdit({action:'deliveryEdit'})} disabled={!data.suppliers.length}>Entrega puntual</Button><Button variant="outline" onClick={exportList} permission="suppliers.export">Exportar entregas CSV</Button></div></div>
 {edit&&<Form key={edit.action+edit.id+edit.supplier} title={edit.action==='supplierProfile'?'Ficha y frecuencia habitual':edit.action==='deliveryGenerate'?'Generar entregas previstas':'Registrar / modificar una entrega'} onClose={()=>setEdit(null)} onSave={submit}>
  {edit.action==='supplierProfile'?<SupplierFields supplier={supplier}/>:edit.action==='deliveryGenerate'?<><p className="form-note">{supplier?.name} · {supplier?.frequency}. Se conservan eventos existentes, reprogramados y cancelados.</p><Field label="Generar desde" name="from" type="date" value={date}/><Field label="Hasta (máximo un año)" name="to" type="date" value={shiftDate(date,30)}/></>:<><Choice label="Proveedor" name="supplier" value={delivery?.supplier??edit.supplier} options={data.suppliers.map(s=>[s.id,s.name])}/><Field label="Fecha prevista (vacío: A confirmar)" name="date" type="date" value={delivery?.date??''} required={false}/><Field label="Límite para el pedido (opcional)" name="deadline" type="date" value={delivery?.deadline??''} required={false}/><Choice label="Estado de esta entrega" name="status" value={delivery?.status??'Prevista'} options={['Prevista','Confirmada','Realizada','Reprogramada','Cancelada']}/><Choice label="Compra vinculada" name="expense" value={delivery?.expense??''} options={[['','Sin compra vinculada'],...data.expenses.map(e=>[e.id,`${e.supplier} · ${e.label} · ${e.date}`] as [string,string])]}/><Text label="Observación / motivo de reprogramación" name="observation" value={delivery?.observation}/><p className="form-note">Marcar realizada registra la visita. La mercadería se recibe desde Compras y gastos; aquí no se recibe ni se paga.</p></>}
 </Form>}
 <div className="planning-filters"><Choice label="Proveedor" name="supplier-filter" value={filter} onChange={setFilter} options={['Todos',...data.suppliers.map(s=>[s.id,s.name] as [string,string])]}/><Choice label="Estado" name="delivery-filter" value={state} onChange={setState} options={['Todos','Prevista','Confirmada','Realizada','Reprogramada','Cancelada']}/><label className="field"><span>Desde</span><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Hasta</span><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 <div className="planning-entities">{entities.map(s=>{const next=data.supplier_deliveries.filter(e=>e.supplier===s.id&&e.date&&e.date>=date&&!['Realizada','Cancelada'].includes(e.status)).sort((a,b)=>a.date!.localeCompare(b.date!))[0];return <article key={s.id}><h3>{s.name}</h3><p>{s.contact||'Contacto sin registrar'} · {JSON.parse(s.rubros).join(', ')}</p><p>{frequencyLabel(s)} · Próxima entrega: {next?.date??'A confirmar'} · Pedido hasta: {next?.deadline??'A confirmar'}</p><p>{s.observation}</p><div className="meal-row-actions"><Button variant="outline" onClick={()=>setEdit({action:'supplierProfile',id:s.id})} permission="suppliers.edit">Editar ficha</Button><Button variant="outline" onClick={()=>setEdit({action:'deliveryGenerate',supplier:s.id})} permission="suppliers.create">Generar agenda</Button><Button variant="outline" permission="suppliers.create" onClick={()=>setEdit({action:'deliveryEdit',supplier:s.id})}>Entrega puntual</Button></div></article>;})}</div>
 <MonthCalendar date={date} selected={selected} onSelect={d=>{setSelected(d);setFrom(d);setTo(d);}} summary={d=>{const n=events.filter(e=>e.date===d).length;return n?`${n} entregas`:'';}}/>
 <h3 className="planning-subheading">Entregas del período · {from} a {to}</h3><div className="table-wrap"><table className="supply-table"><thead><tr>{['Proveedor','Fecha / pedido','Estado','Compra','Observaciones','Acciones'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{listed.map(e=>{const s=data.suppliers.find(s=>s.id===e.supplier)!,expense=data.expenses.find(x=>x.id===e.expense);return <tr key={e.id}><td>{s.name}<small>{s.contact}</small></td><td>{e.date??'A confirmar'}<small>Pedido: {e.deadline??'A confirmar'} · Original: {e.original_date??'A confirmar'}</small></td><td>{e.status}</td><td>{expense?<><span>{expense.label} {Number.isFinite(expense.amount)&&<>· {currency(expense.amount)}</>}</span><Button variant="outline" permission="purchases.view" onClick={()=>onPurchase(expense.id)}>Ver compra / recepción</Button></>:'Sin vínculo'}</td><td>{e.observation}<small>{e.responsible}</small></td><td>{!['Realizada','Cancelada'].includes(e.status)&&<Button variant="outline" onClick={()=>setEdit({action:'deliveryEdit',id:e.id,supplier:e.supplier})} permission="suppliers.edit">Modificar esta entrega</Button>}</td></tr>;})}{!listed.length&&<tr><td colSpan={6}>Sin entregas para este período. Las fechas no conocidas quedan A confirmar.</td></tr>}</tbody></table></div><History logs={data.audit_log} actions={['supplierProfile','deliveryGenerate','deliveryEdit']} entity={filter==='Todos'?undefined:filter}/></section>;
}
