'use client';

import { Input } from '@/components/ui/input';
import { hotelTimeZone,monthDates } from '@/lib/hotel-planning';
import type { HotelData,PersonnelData } from '@/lib/hotel-types';
import { serializeCsv } from '@/lib/hotel-view';
import { ActionButton as Button,SessionResponsible } from '@/modules/access/context';
import { useRef,useState,type FormEvent,type ReactNode } from 'react';
export type Save=(action:string,values:unknown)=>Promise<void>;
export type Props={data:HotelData;date:string;onSave:Save};
export const weekdays=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
export type StaffProps={data:PersonnelData;date:string;onSave:Save};
export function Field({label,name,value='',type='text',required=true}:{label:string;name:string;value?:string|number;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><Input name={name} type={type} defaultValue={value} required={required}/></label>;}
export function Text({label,name,value='',required=false}:{label:string;name:string;value?:string;required?:boolean}){return <label className="field planning-text"><span>{label}</span><textarea className="control" name={name} defaultValue={value} required={required} rows={3}/></label>;}
export function Choice({label,name,options,value='',onChange,multiple=false}:{label:string;name:string;options:(string|[string,string])[];value?:string|string[];onChange?:(v:string)=>void;multiple?:boolean}){return <label className="field"><span>{label}</span><select className="control" name={name} multiple={multiple} value={onChange?value:undefined} defaultValue={onChange?undefined:value||undefined} onChange={e=>onChange?.(e.target.value)}>{options.map(o=>{const [v,l]=typeof o==='string'?[o,o]:o;return <option key={v} value={v}>{l}</option>;})}</select></label>;}
export function Form({title,children,onSave,onClose}:{title:string;children:ReactNode;onSave:(values:Record<string,FormDataEntryValue>,fd:FormData)=>Promise<void>;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;const fd=new FormData(e.currentTarget);lock.current=true;setBusy(true);setError('');try{await onSave(Object.fromEntries(fd),fd);onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{lock.current=false;setBusy(false);}}
 return <form className="entry-form planning-editor" onSubmit={submit}><fieldset disabled={busy}><h3>{title}</h3><div className="form-grid">{children}<SessionResponsible/></div>{error&&<p role="alert" className="notice error">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Volver</Button><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar'}</Button></div></fieldset></form>;
}
export function download(name:string,rows:(string|number)[][]){const url=URL.createObjectURL(new Blob([serializeCsv(rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url);}
export function HistoryDetails({value}:{value:unknown}):ReactNode{
 if(Array.isArray(value))return value.map((v,i)=><div key={i}><HistoryDetails value={v}/></div>);
 if(!value||typeof value!=='object')return <p>Sin registro anterior.</p>;
 const labels:Record<string,string>={name:'Nombre',contact:'Contacto',rubros:'Rubros',frequency:'Frecuencia',lead_days:'Días antes para el pedido',leadDays:'Días antes para el pedido',date:'Fecha',original_date:'Fecha original',deadline:'Límite del pedido',from:'Origen / desde',to:'Destino / hasta',days:'Días del período',service:'Servicio',dishes:'Platos',alternatives:'Alternativas declaradas',conditions:'Condiciones indicadas',status:'Estado',observation:'Observaciones',responsible:'Responsable declarado',role:'Función',active:'Activo',kind:'Clase',start:'Inicio previsto',end:'Fin previsto',startDate:'Día de inicio',endDate:'Día de fin',startTime:'Hora de inicio',endTime:'Hora de fin',attendance:'Asistencia',actual_start:'Inicio real',actual_end:'Fin real',actualStart:'Inicio real',actualEnd:'Fin real',author:'Autor original',type:'Tipo de novedad',description:'Descripción',followup:'Seguimiento',overwrite:'Reemplazo confirmado',acknowledge:'Excepción confirmada'};
 return <dl className="planning-history-fields">{Object.entries(value).filter(([k,v])=>labels[k]&&v!==null&&v!=='').map(([k,v])=><div key={k}><dt>{labels[k]}</dt><dd>{typeof v==='boolean'?v?'Sí':'No':k==='rubros'?Array.isArray(v)?v.join(', '):JSON.parse(String(v)).join(', '):String(v)}</dd></div>)}</dl>;
}
export function History({logs,actions,entity}:{logs:HotelData['audit_log'];actions:string[];entity?:string}){const names:Record<string,string>={supplierProfile:'Ficha y frecuencia de proveedor',deliveryGenerate:'Generación de entregas previstas',deliveryEdit:'Entrega particular',menuPlan:'Planificación de menú',menuCopy:'Copia de menú',menuActual:'Menú efectivamente servido',staffEmployee:'Ficha de empleado',staffEvent:'Planificación de turno / ausencia',staffAttendance:'Asistencia registrada',staffReport:'Novedad y seguimiento'};return <details className="planning-history"><summary>Historial de modificaciones</summary>{logs.filter(a=>actions.includes(a.action)).filter(a=>{if(!entity)return true;const p=JSON.parse(a.detail),d=p.input??p;return [d.id,d.supplier,d.employee,p.after?.id,p.before?.id].includes(entity);}).sort((a,b)=>b.created.localeCompare(a.created)).map(a=>{const p=JSON.parse(a.detail),d=p.input??p;return <div key={a.id}><b>{new Date(a.created).toLocaleString('es-AR',{timeZone:hotelTimeZone})} · {d.responsible??a.actor}</b><p>{names[a.action]}</p><small>{d.date??d.startDate??d.from??''} · {d.status??d.attendance??d.frequency??''}</small><details><summary>Ver detalle anterior y nuevo</summary><h4>Anterior</h4><HistoryDetails value={p.before}/><h4>Registrado</h4><HistoryDetails value={d}/></details></div>;})}</details>;}
export function MonthCalendar({date,selected,onSelect,summary}:{date:string;selected:string;onSelect:(date:string)=>void;summary:(day:string)=>ReactNode}){
 const dates=monthDates(date),offset=(new Date(dates[0]+'T00:00:00Z').getUTCDay()+6)%7;
 return <div className="planning-calendar"><h3>{new Date(date.slice(0,7)+'-15T12:00:00Z').toLocaleDateString('es-AR',{timeZone:hotelTimeZone,month:'long',year:'numeric'})}</h3><div className="planning-days">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{dates.map(day=><button type="button" key={day} aria-label={'Consultar '+day} aria-pressed={day===selected} className={day===selected?'selected':''} onClick={()=>onSelect(day)}><b>{Number(day.slice(8))}</b><span>{summary(day)}</span></button>)}</div></div>;
}