'use client';

import { Input } from '@/components/ui/input';
import { kitchenRows,kitchenTotals,services,type Service } from '@/lib/hotel-meals';
import { monthDates,shiftDate } from '@/lib/hotel-planning';
import type { HotelData } from '@/lib/hotel-types';
import { ActionButton as Button } from '@/modules/access/context';
import { Choice,download,Field,Form,History,MonthCalendar,Props,Text } from '@/modules/shared/planning-ui';
import { useState } from 'react';
export function MenuDailySummary({data,date,service}:{data:HotelData;date:string;service:Service}){
 const menu=data.menu_plans?.find(m=>m.date===date&&m.service===service),actual=data.menu_actuals?.find(m=>m.plan===menu?.id);
 return <div className="menu-summary"><b>Menú previsto · {service}: {menu?.status??'Sin planificar'}</b><p>{menu?.dishes??'No hay platos cargados para este servicio.'}</p>{menu&&<><p>Alternativas declaradas: {menu.alternatives||'Sin registrar'}</p><p>Condiciones indicadas: {menu.conditions||'Sin registrar'}</p><p>{menu.observation} · {menu.responsible}</p></>}{actual&&<><b>Menú efectivamente servido</b><p>{actual.dishes}</p><p>Alternativas: {actual.alternatives||'Sin registrar'} · Condiciones: {actual.conditions||'Sin registrar'}</p><p>{actual.observation} · {actual.responsible}</p></>}<small>Los nombres de los platos no determinan si son aptos para una restricción.</small></div>;
}
export function MenuPlanner({data,date,onSave}:Props){
 const [selection,setSelection]=useState<{base:string;day:string}|null>(null),day=selection?.base===date?selection.day:date;
 const [service,setService]=useState<Service>('Cena'),[edit,setEdit]=useState<{action:string;plan?:string}|null>(null),[copyFrom,setCopyFrom]=useState(day),[copyTo,setCopyTo]=useState(shiftDate(day,7)),[copyDays,setCopyDays]=useState('7'),[overwrite,setOverwrite]=useState(false);
 const plan=data.menu_plans.find(m=>m.id===edit?.plan),actual=data.menu_actuals.find(m=>m.plan===plan?.id);
 const source=data.menu_plans.filter(m=>m.date>=copyFrom&&m.date<=shiftDate(copyFrom,Number(copyDays)-1));
 const targets=source.map(m=>{const offset=Math.round((Date.parse(m.date)-Date.parse(copyFrom))/86400000),id=shiftDate(copyTo,offset)+':'+m.service;return {id,version:data.menu_plans.find(t=>t.id===id)?.version??-1};});
 async function submit(v:Record<string,FormDataEntryValue>){if(!edit)return;if(edit.action==='menuCopy')await onSave(edit.action,{...v,from:copyFrom,to:copyTo,days:Number(copyDays),overwrite,expected:targets});else if(edit.action==='menuActual')await onSave(edit.action,{...v,id:actual?.id??'',version:actual?.version??0,plan:plan!.id});else await onSave(edit.action,{...v,id:plan?.id??'',version:plan?.version??0});}
 function exportMonth(){const rows:(string|number)[][]=[['Fecha','Servicio','Estado','Menú previsto','Alternativas declaradas','Condiciones','Observaciones','Huéspedes previstos','Externos previstos','Total','Restricciones registradas','Menú servido','Responsable']];for(const d of monthDates(date))for(const s of services){const m=data.menu_plans.find(m=>m.date===d&&m.service===s),a=data.menu_actuals.find(a=>a.plan===m?.id),k=kitchenRows(data,d,s),n=kitchenTotals(k);rows.push([d,s,m?.status??'Sin planificar',m?.dishes??'',m?.alternatives??'',m?.conditions??'',m?.observation??'',n.hotel,n.external,n.total,k.filter(r=>r.restrictions).map(r=>`${r.name}: ${r.restrictions} (${r.state})`).join(' · '),a?.dishes??'',m?.responsible??'']);}download('menu-'+date.slice(0,7),rows);}
 return <section className="panel planning-panel"><div className="panel-heading"><div><h2>Menú mensual</h2><p>Planificación y menú servido, sin compras ni descuentos de stock.</p></div><div className="meal-row-actions"><Button variant="outline" onClick={()=>{setCopyFrom(day);setCopyTo(shiftDate(day,7));setOverwrite(false);setEdit({action:'menuCopy'});}} permission="menu.create">Copiar día / semana</Button><Button variant="outline" onClick={exportMonth} permission="menu.export">Exportar menú CSV</Button></div></div>
 {edit&&<Form key={edit.action+edit.plan} title={edit.action==='menuCopy'?'Copiar planificación':edit.action==='menuActual'?'Registrar menú efectivamente servido':'Menú previsto por servicio'} onClose={()=>setEdit(null)} onSave={submit}>
  {edit.action==='menuCopy'?<><label className="field"><span>Origen</span><Input type="date" value={copyFrom} onChange={e=>setCopyFrom(e.target.value)} required/></label><label className="field"><span>Destino</span><Input type="date" value={copyTo} onChange={e=>setCopyTo(e.target.value)} required/></label><Choice label="Período a copiar" name="days" value={copyDays} onChange={setCopyDays} options={[['1','Un día'],['7','Una semana']]}/><p className="form-note">{source.length} servicios para copiar. {targets.filter(t=>t.version>=0).length} ya existen en el destino. Las copias quedan Borrador; los menús servidos conservan su registro.</p><label className="tick"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>Confirmo reemplazar los menús previstos que ya existan en esas fechas</label><p className="form-note">Destino: {copyTo} a {shiftDate(copyTo,Number(copyDays)-1)}. Sin confirmación no se sobrescribe nada.</p></>:<>{edit.action==='menuPlan'?<><Field label="Fecha del menú" name="date" type="date" value={plan?.date??day}/><Choice label="Servicio" name="service" value={plan?.service??service} options={[...services]}/><Choice label="Estado de planificación" name="status" value={plan?.status??'Borrador'} options={['Borrador','Confirmado']}/></>:<p className="form-note">{plan?.date} · {plan?.service}. Se conserva una copia del menú previsto; no marca la asistencia de las personas.</p>}<Text label="Platos / menú fijo" name="dishes" required value={edit.action==='menuActual'?actual?.dishes:plan?.dishes}/><Text label="Alternativas previstas, cargadas expresamente" name="alternatives" value={edit.action==='menuActual'?actual?.alternatives:plan?.alternatives}/><Text label="Restricciones / condiciones declaradas para esas alternativas" name="conditions" value={edit.action==='menuActual'?actual?.conditions:plan?.conditions}/><Text label={edit.action==='menuActual'?'Observación / motivo de diferencia':'Observaciones'} name="observation" required={edit.action==='menuActual'} value={edit.action==='menuActual'?actual?.observation:plan?.observation}/></>}
 </Form>}
 <MonthCalendar date={date} selected={day} onSelect={d=>setSelection({base:date,day:d})} summary={d=>{const ms=data.menu_plans.filter(m=>m.date===d);return ms.length?`${ms.length}/3 · ${ms.filter(m=>m.status==='Confirmado').length} confirmados`:'Sin planificar';}}/>
 <div className="planning-filters"><Choice label="Servicio del detalle" name="menu-service" value={service} onChange={v=>setService(v as Service)} options={[...services]}/></div>
 <div className="planning-daily"><h3>Detalle del {day} · {service}</h3><MenuDailySummary data={data} date={day} service={service}/><div className="meal-row-actions"><Button onClick={()=>setEdit({action:'menuPlan',plan:data.menu_plans.find(m=>m.date===day&&m.service===service)?.id})} permission={plan?'menu.edit':'menu.create'}>Editar / cargar menú previsto</Button><Button variant="outline" disabled={!data.menu_plans.some(m=>m.date===day&&m.service===service)} onClick={()=>setEdit({action:'menuActual',plan:data.menu_plans.find(m=>m.date===day&&m.service===service)?.id})} permission="menu.edit">Registrar / editar menú servido</Button></div>{(()=>{const rows=kitchenRows(data,day,service),totals=kitchenTotals(rows);return <><p className="planning-count">Huéspedes: {totals.hotel} · Externos: {totals.external} · Total previsto: {totals.total}</p>{rows.filter(r=>r.restrictions||r.preferences||r.observation||r.reason).map(r=><div className="planning-condition" key={r.key}><b>Hab. {r.room} · {r.name} · {r.expected} prevista · {r.state}</b><p>Restricciones: {r.restrictions||'Sin registrar'}</p><p>Preferencias: {r.preferences||'Sin registrar'}</p><p>{r.observation} {r.reason&&'Suspensión: '+r.reason}</p></div>)}</>;})()}
 {(()=>{const m=data.menu_plans.find(m=>m.date===day&&m.service===service),a=data.menu_actuals.find(a=>a.plan===m?.id);return a&&<details className="detail-disclosure"><summary>Menú previsto conservado al registrar el servicio</summary><p>{JSON.parse(a.planned_snapshot).dishes}</p><p>{JSON.parse(a.planned_snapshot).alternatives} · {JSON.parse(a.planned_snapshot).conditions}</p></details>;})()}</div><History logs={data.audit_log} actions={['menuPlan','menuCopy','menuActual']}/></section>;
}
