'use client';

import { Input } from '@/components/ui/input';
import { dueLabel,receiptPending,supplierBalance,supplierCsv } from '@/lib/hotel-supply-view';
import { currency,serializeCsv } from '@/lib/hotel-view';
import { ActionButton as Button,useIdentity } from '@/modules/access/context';
import { can } from '@/modules/access/permissions';
import { accounts,Choice,Editor,Field,History,Props,rubros,Table } from '@/modules/shared/supply-ui';
import { useState } from 'react';
export function Purchases({data,date,onSave,initialExpense=''}:Props & {initialExpense?:string}){
 const identity=useIdentity(),financial=!identity||can(identity,'purchases.financial');
 const [form,setForm]=useState(data.purchase_lines.some(l=>l.expense===initialExpense&&receiptPending(data,l)>0)?'purchaseReceive':''),[selected,setSelected]=useState(initialExpense),[type,setType]=useState('Productos'),[lines,setLines]=useState([{key:0,product:data.products[0]?.id??'',qty:1,cost:0,category:'Bebidas'}]);
 const [supplier,setSupplier]=useState(data.expenses.find(e=>e.id===initialExpense)?.supplier??''),[rubro,setRubro]=useState('Todos'),[area,setArea]=useState('Todas'),[state,setState]=useState('Todos'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[delivery,setDelivery]=useState('Todas');
 const close=()=>setForm('');const begin=(f:string,id='')=>{setSelected(id);setForm(f);};
 const selectedExpense=data.expenses.find(e=>e.id===selected);
 const selectedLines=data.purchase_lines.filter(l=>l.expense===selected);
 const filtered=data.expenses.filter(e=>{const bal=supplierBalance(data,e,date),ls=data.purchase_lines.filter(l=>l.expense===e.id),doc=data.purchase_documents.find(d=>d.expense===e.id);return e.date<=date&&(!from||e.date>=from)&&(!to||e.date<=to)&&e.supplier.toLowerCase().includes(supplier.toLowerCase())&&(area==='Todas'||e.area===area)&&(rubro==='Todos'||e.category===rubro||ls.some(l=>l.category===rubro))&&(state==='Todos'||bal.status===state||state==='Vencido'&&!!e.due&&e.due<date&&bal.balance>0||state==='Sin vencimiento'&&!e.due&&bal.balance>0||state==='Próximo a vencer'&&dueLabel(e,bal.balance,date).startsWith('Próximo'))&&(delivery==='Todas'||doc?.type==='Productos'&&(delivery==='Recibidas'?!ls.some(l=>receiptPending(data,l,date)>0):ls.some(l=>receiptPending(data,l,date)>0)));}).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const exportList=()=>{const url=URL.createObjectURL(new Blob([financial?supplierCsv(data,filtered,date):serializeCsv([['Proveedor','Concepto','Fecha','Productos / cantidades pendientes'],...filtered.map(e=>[e.supplier,e.label,e.date,data.purchase_lines.filter(l=>l.expense===e.id).map(l=>(data.products.find(p=>p.id===l.product)?.name??'')+': '+receiptPending(data,l,date)).join(' | ')])])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`proveedores-${date}.csv`;a.click();URL.revokeObjectURL(url);};
 const total=lines.reduce((n,l)=>n+Math.round(l.qty*Math.round(l.cost*100)),0);
 return <section className="panel"><div className="panel-heading"><div><h2>Compras, recepción y vencimientos</h2><p>Pagos y recepción independientes. Consulta al {date}.</p></div><div className="meal-row-actions"><Button onClick={()=>begin('purchaseDocument')} permission="purchases.create">Nuevo comprobante</Button><Button variant="outline" onClick={exportList} permission="purchases.export">Exportar proveedores CSV</Button></div></div>
 {form&&<Editor key={form+selected} title={form==='purchaseDocument'?'Compra o gasto':form==='purchaseReceive'?'Recibir productos':'Registrar pago a proveedor'} date={date} onCancel={close} onSubmit={v=>onSave(form,form==='purchaseDocument'?{...v,type,received:v.received==='on',lines:type==='Productos'?lines.map(({product,qty,cost,category})=>({product,qty,cost,category})):[]}:form==='purchaseReceive'?{...v,expense:selected,lines:selectedLines.map(l=>({line:l.id,qty:Number(v['receive-'+l.id])})).filter(l=>l.qty>0)}:{...v,expense:selected})}>
  {form==='purchaseDocument'&&<><Field label="Proveedor" name="supplier"/><Field label="Número de comprobante (opcional)" name="invoice" required={false}/><Field label="Concepto" name="label"/><Field label="Vencimiento acordado (opcional)" name="due" type="date" required={false}/><Choice label="Clase" name="type" value={type} onChange={setType} options={['Productos','Servicio','Administrativo']}/><Choice label="Actividad" name="area" options={['Hotel','Restaurante','Compartido']}/><Choice label="Tipo de gasto" name="kind" options={['Variable','Fijo']}/>{type!=='Productos'?<><Choice label="Rubro" name="category" options={type==='Servicio'?['Electricidad','Internet','Mantenimiento','Otros servicios']:['Administración','Otros gastos']}/><Field label="Importe total (ARS)" name="amount" type="number" min="0.01" step="0.01"/></>:<><input name="category" type="hidden" value="Productos"/><div className="supply-lines">{lines.map((l,i)=><div key={l.key} className="supply-line"><Choice label="Producto" name={'product-'+i} value={l.product} onChange={product=>{const p=data.products.find(p=>p.id===product);setLines(lines.map((v,j)=>i===j?{...v,product,category:p?.category==='Limpieza y amenities'?'Limpieza':p?.category??'Bebidas'}:v));}} options={data.products.map(p=>[p.id,`${p.name} (${p.unit})`])}/><Choice label="Rubro" name={'rubro-'+i} value={l.category} onChange={category=>setLines(lines.map((v,j)=>i===j?{...v,category}:v))} options={rubros}/><label className="field"><span>Cantidad</span><Input required type="number" min="0.001" step="0.001" value={l.qty} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,qty:Number(e.target.value)}:v))}/></label><label className="field"><span>Costo por unidad (ARS)</span><Input required type="number" min="0.01" step="0.01" value={l.cost} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,cost:Number(e.target.value)}:v))}/></label><span>{currency(Math.round(l.qty*Math.round(l.cost*100)))}</span><Button type="button" variant="outline" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>i!==j))}>Quitar línea</Button></div>)}<Button type="button" variant="outline" onClick={()=>setLines([...lines,{key:Math.max(...lines.map(l=>l.key))+1,product:data.products[0]?.id??'',qty:1,cost:0,category:data.products[0]?.category??'Bebidas'}])} permission="purchases.create">Agregar producto</Button><strong className="supply-total">Total calculado: {currency(total)}</strong></div><label className="tick"><input name="received" type="checkbox"/>Recibido en su totalidad</label><p className="form-note">Sin esta confirmación la compra queda pendiente de entrega. El pago se registra por separado.</p></>}</>}
  {form==='purchaseReceive'&&<><p className="form-note">{selectedExpense?.supplier} · {selectedExpense?.label}. Indicá solamente lo que llegó; cero no registra una recepción.</p>{selectedLines.map(l=><Field key={l.id} label={`${data.products.find(p=>p.id===l.product)?.name} · pendientes ${receiptPending(data,l)}`} name={'receive-'+l.id} type="number" min="0" step="0.001" value="0"/>)}</>}
  {form==='supplierPay'&&<><p className="form-note">{selectedExpense?.supplier} · {selectedExpense?.label}. Saldo actual {currency(selectedExpense?supplierBalance(data,selectedExpense).balance:0)}. Pagar no recibe stock.</p><Field label="Importe a pagar (ARS)" name="amount" type="number" min="0.01" step="0.01"/><Choice label="Cuenta utilizada" name="account" options={accounts}/><Field label="Referencia del pago" name="reference" required={false}/></>}
 </Editor>}
 <div className="supply-filters"><label className="field"><span>Proveedor</span><Input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><Choice label="Rubro" name="filter-rubro" value={rubro} onChange={setRubro} options={['Todos',...rubros,'Electricidad','Internet','Mantenimiento','Otros servicios','Administración','Otros gastos','Servicios','Insumos']}/><Choice label="Actividad" name="filter-area" value={area} onChange={setArea} options={['Todas','Hotel','Restaurante','Compartido']}/>{financial&&<Choice label="Estado / vencimiento" name="filter-state" value={state} onChange={setState} options={['Todos','Pendiente','Parcialmente pagado','Pagado','Vencido','Próximo a vencer','Sin vencimiento']}/>}<Choice label="Recepción" name="filter-delivery" value={delivery} onChange={setDelivery} options={['Todas','Pendientes','Recibidas']}/><label className="field"><span>Comprobantes desde</span><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Hasta</span><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 <Table headers={(financial?['Proveedor / concepto','Comprobante / rubros','Actividad / tipo','Fecha / vencimiento','Total / pagos / saldo','Estado','Recepción / historial','Acciones']:['Proveedor / concepto','Comprobante / rubros','Actividad / tipo','Fecha','Recepción / historial','Acciones'])} rows={filtered.map(e=>{const b=supplierBalance(data,e,date),doc=data.purchase_documents.find(d=>d.expense===e.id),ls=data.purchase_lines.filter(l=>l.expense===e.id);return [<span key="e">{e.supplier}<small>{e.label}</small></span>,<span key="doc">{doc?.invoice||'Sin número'}<small>{doc?.type??'Histórico'} · {ls.length?[...new Set(ls.map(l=>l.category))].join(', '):e.category}</small></span>,`${e.area} · ${e.kind}`,<span key="date">{e.date}{financial&&<small>{e.due||'Vencimiento sin definir'} · {dueLabel(e,b.balance,date)}</small>}</span>,financial?<span key="money">{currency(e.amount)}<small>Pagos: {currency(b.paid)}</small><b>Saldo: {currency(b.balance)}</b></span>:null,financial?b.status:null,<details key="receive"><summary>{doc?.type==='Productos'?ls.some(l=>receiptPending(data,l,date)>0)?'Pendiente / parcial':'Recibido':doc?'Sin stock':'Histórico · sin reinterpretar'}</summary>{ls.map(l=><div key={l.id}>{data.products.find(p=>p.id===l.product)?.name}: {l.qty} · pendientes {receiptPending(data,l,date)} {financial&&<>· costo {currency(l.cost)}</>}{data.purchase_receipts.filter(r=>r.line===l.id).map(r=><small key={r.id}>{r.date} · recibido {r.qty} · {r.responsible} {r.observation}</small>)}</div>)}{data.cash_movements.filter(m=>m.ref===e.id&&m.kind==='Pago').map(m=>{const p=data.supplier_payment_details.find(p=>p.cash===m.id);return <div key={m.id}>{m.date} · {m.account} · {currency(-m.amount)}<small>{p?.reference} · {p?.responsible??'Histórico'}</small></div>;})}<p>{doc?.responsible} {doc?.observation}</p></details>,<div key="actions" className="meal-row-actions">{supplierBalance(data,e).balance>0&&<Button variant="outline" onClick={()=>begin('supplierPay',e.id)} permission="purchases.pay">Pagar</Button>}{ls.some(l=>receiptPending(data,l)>0)&&<Button variant="outline" onClick={()=>begin('purchaseReceive',e.id)} permission="purchases.receive">Recibir</Button>}</div>].filter((_,i)=>financial||![4,5].includes(i));})}/>
 <History data={data} actions={['purchaseDocument','purchaseReceive','supplierPay']}/></section>;
}
