'use client';
import { useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { HotelData } from '@/lib/hotel-types';
import { currency } from '@/lib/hotel-view';
import { dispatchStatus, dueLabel, receiptPending, supplierBalance, supplierCsv, tableTotal } from '@/lib/hotel-supply-view';
type Props={data:HotelData;date:string;onSave:(action:string,values:unknown)=>Promise<void>};
const accounts=['Efectivo','Banco','Billetera'],rubros=['Bebidas','Alimentos','Limpieza','Amenities','Reutilizables'];
function Field({label,name,type='text',value='',required=true,min,step}:{label:string;name:string;type?:string;value?:string|number;required?:boolean;min?:string;step?:string}){return <label className="field"><span>{label}</span><Input name={name} type={type} defaultValue={value} required={required} min={min} step={step}/></label>;}
function Choice({label,name,options,value,onChange}:{label:string;name:string;options:(string|[string,string])[];value?:string;onChange?:(s:string)=>void}){return <label className="field"><span>{label}</span><select className="control" name={name} value={onChange?value:undefined} defaultValue={onChange?undefined:value} onChange={e=>onChange?.(e.target.value)}>{options.map(o=>{const [v,l]=typeof o==='string'?[o,o]:o;return <option key={v} value={v}>{l}</option>;})}</select></label>;}
function Editor({title,date,children,onSubmit,onCancel}:{title:string;date:string;children:ReactNode;onSubmit:(v:Record<string,FormDataEntryValue>)=>Promise<void>;onCancel:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await onSubmit(Object.fromEntries(new FormData(e.currentTarget)));onCancel();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{lock.current=false;setBusy(false);}}
 return <form className="entry-form supply-editor" onSubmit={submit}><h3>{title}</h3><div className="form-grid"><Field label="Fecha del movimiento" name="date" type="date" value={date}/><Field label="Responsable declarado" name="responsible"/><Field label="Observación" name="observation" required={false}/>{children}</div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" onClick={onCancel} disabled={busy}>Volver</Button><Button disabled={busy}>{busy?'Guardando…':'Guardar'}</Button></div></form>;
}
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="table-wrap"><table className="supply-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length}>No hay registros.</td></tr>}</tbody></table></div>;}
function History({data,actions}:{data:HotelData;actions:string[]}){const names:Record<string,string>={beverageAccount:'Apertura de cuenta',beverageDispatch:'Despacho de bebida',beverageSettle:'Cierre de cuenta',beverageReturn:'Devolución física',beverageCorrect:'Corrección de despacho',purchaseDocument:'Nuevo comprobante',purchaseReceive:'Recepción de productos',supplierPay:'Pago a proveedor'};return <details className="supply-history"><summary>Historial de movimientos</summary>{data.audit_log.filter(a=>actions.includes(a.action)).sort((a,b)=>b.created.localeCompare(a.created)).map(a=>{const detail=JSON.parse(a.detail),d=detail.input??detail;return <div key={a.id}><b>{names[a.action]??a.action}</b> · {new Date(a.created).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'})}<p>{d.responsible??a.actor} · {d.reason??d.label??d.reference??d.table??''} {d.observation??''}</p><small>{d.qty?`Cantidad: ${d.qty}. `:''}{d.amount?`Importe: ${currency(Number(d.amount)*100)}. `:''}{d.lines?`${d.lines.length} líneas. `:''}{d.method??d.mode??''}</small></div>;})}</details>;}
export function Beverages({data,date,onSave}:Props){
 const [form,setForm]=useState(''),[selected,setSelected]=useState(''),[destination,setDestination]=useState('Mesa'),[mode,setMode]=useState('Pendiente'),[product,setProduct]=useState(data.products.find(p=>p.category==='Bebidas')?.id??'');
 const open=data.beverage_accounts.filter(a=>!data.beverage_settlements.some(s=>s.table_account===a.id));
 const bookings=data.bookings.filter(b=>['Confirmada','Alojado'].includes(b.status));
 const close=()=>setForm('');const begin=(f:string,id='')=>{setSelected(id);setForm(f);};
 const target=data.sales.find(s=>s.id===selected);
 const returned=(id:string)=>data.beverage_returns.filter(r=>r.dispatch===id).reduce((n,r)=>n+r.qty,0);
 return <section className="panel spaced"><div className="panel-heading"><div><h2>Bebidas y cuentas de mesa</h2><p>Destino físico y cobro se registran por separado.</p></div><div className="meal-row-actions"><Button variant="outline" onClick={()=>begin('beverageAccount')}>Abrir cuenta de mesa</Button><Button onClick={()=>begin('beverageDispatch')}>Despachar bebida</Button></div></div>
 {form&&<Editor key={form+selected} title={form==='beverageAccount'?'Abrir una cuenta nueva':form==='beverageDispatch'?'Registrar despacho':form==='beverageSettle'?'Cerrar cuenta de mesa':form==='beverageReturn'?'Devolución física al stock':'Corregir un despacho'} date={date} onCancel={close} onSubmit={v=>onSave(form,form==='beverageDispatch'?{...v,tableAccount:destination==='Mesa'?v.tableAccount:'',booking:mode==='Estadía'||destination==='Estadía'?v.booking:'',mode:['Cortesía','Interno'].includes(destination)?'Sin cobro':mode}:form==='beverageAccount'?v:form==='beverageSettle'?{...v,tableAccount:selected}:{...v,dispatch:selected})}>
  {form==='beverageAccount'&&<><Field label="Mesa / identificador físico" name="table"/><Field label="Hora del hotel" name="time" type="time" value="12:00"/><p className="form-note">Cada apertura crea una cuenta independiente, aunque la mesa se reutilice.</p></>}
  {form==='beverageDispatch'&&<><Field label="Hora del despacho (Buenos Aires)" name="time" type="time" value={new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())}/><Choice label="Bebida" name="product" value={product} onChange={setProduct} options={data.products.filter(p=>p.category==='Bebidas').map(p=>[p.id,p.name])}/><Field label="Cantidad en unidad del producto" name="qty" type="number" min="0.001" step="0.001" value="1"/><Choice label="Destino físico" name="destination" value={destination} onChange={v=>{setDestination(v);setMode(v==='Mesa'?'Pendiente':'Inmediato');}} options={['Mesa','Estadía','Cortesía','Interno']}/>{destination==='Mesa'&&<Choice label="Cuenta de mesa abierta" name="tableAccount" options={open.map(a=>[a.id,`${a.table_name} · ${a.id.slice(0,8)}`])}/>}{!['Cortesía','Interno'].includes(destination)&&<Choice label="Condición de cobro" name="mode" value={mode} onChange={setMode} options={destination==='Mesa'?['Pendiente','Inmediato','Estadía']:['Inmediato','Estadía']}/>}{(destination==='Estadía'||mode==='Estadía')&&<Choice label="Estadía para identificar / cargar" name="booking" options={bookings.map(b=>[b.id,`Hab. ${b.room} · ${b.guest}`])}/>}<Field label="Cliente / referencia" name="customer" value="Cliente de restaurante"/><Field key={product} label="Precio aplicado por unidad (ARS)" name="price" type="number" min="0" step="0.01" value={(data.products.find(p=>p.id===product)?.price??0)/100}/><Choice label="Cuenta para cobro inmediato" name="account" options={accounts}/><Field label="Motivo de cortesía / interno" name="reason" required={['Cortesía','Interno'].includes(destination)}/><p className="form-note">El despacho descuenta stock una vez. Cobrar o transferir después no lo descuenta de nuevo.</p></>}
  {form==='beverageSettle'&&<><p className="form-note">Cuenta {data.beverage_accounts.find(a=>a.id===selected)?.table_name} · {selected.slice(0,8)} · pendiente {currency(tableTotal(data,selected))}</p><Choice label="Cerrar mediante" name="method" options={['Cobro','Estadía']}/><Choice label="Cuenta para el cobro" name="account" options={accounts}/><Choice label="Estadía (para transferir cargos)" name="booking" options={[['','Sin estadía'],...bookings.map(b=>[b.id,`Hab. ${b.room} · ${b.guest}`] as [string,string])]}/></>}
  {(form==='beverageReturn'||form==='beverageCorrect')&&<><p className="form-note">{target?.label} · {target?.qty} despachadas · {returned(selected)} devueltas. La corrección económica no devuelve stock. Los cobros y días cerrados requieren un circuito de regularización pendiente.</p>{form==='beverageReturn'&&<><Field label="Cantidad que regresó en condiciones de venta" name="qty" type="number" min="0.001" step="0.001"/><p className="form-note">Confirmá el regreso físico. Esta operación no devuelve dinero ni anula cargos.</p></>}<Field label="Motivo" name="reason"/></>}
 </Editor>}
 <Table headers={['Mesa / cuenta','Apertura','Pendiente','Estado','Acción']} rows={data.beverage_accounts.slice().sort((a,b)=>b.opened_at.localeCompare(a.opened_at)).map(a=>{const s=data.beverage_settlements.find(s=>s.table_account===a.id);return [<span key="id">{a.table_name}<small>Cuenta {a.id.slice(0,8)}</small></span>,new Date(a.opened_at).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'}),currency(s?0:tableTotal(data,a.id)),s?`Cerrada · ${s.method}`:'Abierta',!s&&<Button variant="outline" onClick={()=>begin('beverageSettle',a.id)}>Cobrar / transferir</Button>];})}/>
 <h3 className="supply-subheading">Despachos del {date}</h3><Table headers={['Hora / destino','Bebida','Cantidad / devolución','Precio / total','Cobro','Responsable / observación','Acciones']} rows={data.beverage_dispatches.filter(d=>data.sales.find(s=>s.id===d.sale)?.date===date).map(d=>{const s=data.sales.find(s=>s.id===d.sale)!;return [<span key="dest">{d.time} · {d.destination}<small>{data.beverage_accounts.find(a=>a.id===d.table_account)?.table_name??s.customer} {d.table_account?.slice(0,8)}</small></span>,s.label,`${s.qty} / devueltas ${returned(s.id)}`,<span key="money">{currency(d.price)} / {currency(s.amount)}</span>,dispatchStatus(data,s.id),<span key="who">{d.responsible}<small>{d.reason} {d.observation}</small></span>,<div key="actions" className="meal-row-actions">{returned(s.id)<s.qty&&<Button variant="outline" onClick={()=>begin('beverageReturn',s.id)}>Devolución física</Button>}{!data.beverage_corrections.some(c=>c.dispatch===s.id)&&<Button variant="outline" onClick={()=>begin('beverageCorrect',s.id)}>Corregir</Button>}</div>];})}/>
 <History data={data} actions={['beverageAccount','beverageDispatch','beverageSettle','beverageReturn','beverageCorrect']}/></section>;
}
export function Purchases({data,date,onSave,initialExpense=''}:Props & {initialExpense?:string}){
 const [form,setForm]=useState(data.purchase_lines.some(l=>l.expense===initialExpense&&receiptPending(data,l)>0)?'purchaseReceive':''),[selected,setSelected]=useState(initialExpense),[type,setType]=useState('Productos'),[lines,setLines]=useState([{key:0,product:data.products[0]?.id??'',qty:1,cost:0,category:'Bebidas'}]);
 const [supplier,setSupplier]=useState(data.expenses.find(e=>e.id===initialExpense)?.supplier??''),[rubro,setRubro]=useState('Todos'),[area,setArea]=useState('Todas'),[state,setState]=useState('Todos'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[delivery,setDelivery]=useState('Todas');
 const close=()=>setForm('');const begin=(f:string,id='')=>{setSelected(id);setForm(f);};
 const selectedExpense=data.expenses.find(e=>e.id===selected);
 const selectedLines=data.purchase_lines.filter(l=>l.expense===selected);
 const filtered=data.expenses.filter(e=>{const bal=supplierBalance(data,e,date),ls=data.purchase_lines.filter(l=>l.expense===e.id),doc=data.purchase_documents.find(d=>d.expense===e.id);return e.date<=date&&(!from||e.date>=from)&&(!to||e.date<=to)&&e.supplier.toLowerCase().includes(supplier.toLowerCase())&&(area==='Todas'||e.area===area)&&(rubro==='Todos'||e.category===rubro||ls.some(l=>l.category===rubro))&&(state==='Todos'||bal.status===state||state==='Vencido'&&!!e.due&&e.due<date&&bal.balance>0||state==='Sin vencimiento'&&!e.due&&bal.balance>0||state==='Próximo a vencer'&&dueLabel(e,bal.balance,date).startsWith('Próximo'))&&(delivery==='Todas'||doc?.type==='Productos'&&(delivery==='Recibidas'?!ls.some(l=>receiptPending(data,l,date)>0):ls.some(l=>receiptPending(data,l,date)>0)));}).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const exportList=()=>{const url=URL.createObjectURL(new Blob([supplierCsv(data,filtered,date)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`proveedores-${date}.csv`;a.click();URL.revokeObjectURL(url);};
 const total=lines.reduce((n,l)=>n+Math.round(l.qty*Math.round(l.cost*100)),0);
 return <section className="panel"><div className="panel-heading"><div><h2>Compras, recepción y vencimientos</h2><p>Pagos y recepción independientes. Consulta al {date}.</p></div><div className="meal-row-actions"><Button onClick={()=>begin('purchaseDocument')}>Nuevo comprobante</Button><Button variant="outline" onClick={exportList}>Exportar proveedores CSV</Button></div></div>
 {form&&<Editor key={form+selected} title={form==='purchaseDocument'?'Compra o gasto':form==='purchaseReceive'?'Recibir productos':'Registrar pago a proveedor'} date={date} onCancel={close} onSubmit={v=>onSave(form,form==='purchaseDocument'?{...v,type,received:v.received==='on',lines:type==='Productos'?lines.map(({product,qty,cost,category})=>({product,qty,cost,category})):[]}:form==='purchaseReceive'?{...v,expense:selected,lines:selectedLines.map(l=>({line:l.id,qty:Number(v['receive-'+l.id])})).filter(l=>l.qty>0)}:{...v,expense:selected})}>
  {form==='purchaseDocument'&&<><Field label="Proveedor" name="supplier"/><Field label="Número de comprobante (opcional)" name="invoice" required={false}/><Field label="Concepto" name="label"/><Field label="Vencimiento acordado (opcional)" name="due" type="date" required={false}/><Choice label="Clase" name="type" value={type} onChange={setType} options={['Productos','Servicio','Administrativo']}/><Choice label="Actividad" name="area" options={['Hotel','Restaurante','Compartido']}/><Choice label="Tipo de gasto" name="kind" options={['Variable','Fijo']}/>{type!=='Productos'?<><Choice label="Rubro" name="category" options={type==='Servicio'?['Electricidad','Internet','Mantenimiento','Otros servicios']:['Administración','Otros gastos']}/><Field label="Importe total (ARS)" name="amount" type="number" min="0.01" step="0.01"/></>:<><input name="category" type="hidden" value="Productos"/><div className="supply-lines">{lines.map((l,i)=><div key={l.key} className="supply-line"><Choice label="Producto" name={'product-'+i} value={l.product} onChange={product=>{const p=data.products.find(p=>p.id===product);setLines(lines.map((v,j)=>i===j?{...v,product,category:p?.category==='Limpieza y amenities'?'Limpieza':p?.category??'Bebidas'}:v));}} options={data.products.map(p=>[p.id,`${p.name} (${p.unit})`])}/><Choice label="Rubro" name={'rubro-'+i} value={l.category} onChange={category=>setLines(lines.map((v,j)=>i===j?{...v,category}:v))} options={rubros}/><label className="field"><span>Cantidad</span><Input required type="number" min="0.001" step="0.001" value={l.qty} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,qty:Number(e.target.value)}:v))}/></label><label className="field"><span>Costo por unidad (ARS)</span><Input required type="number" min="0.01" step="0.01" value={l.cost} onChange={e=>setLines(lines.map((v,j)=>i===j?{...v,cost:Number(e.target.value)}:v))}/></label><span>{currency(Math.round(l.qty*Math.round(l.cost*100)))}</span><Button type="button" variant="outline" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>i!==j))}>Quitar línea</Button></div>)}<Button type="button" variant="outline" onClick={()=>setLines([...lines,{key:Math.max(...lines.map(l=>l.key))+1,product:data.products[0]?.id??'',qty:1,cost:0,category:data.products[0]?.category??'Bebidas'}])}>Agregar producto</Button><strong className="supply-total">Total calculado: {currency(total)}</strong></div><label className="tick"><input name="received" type="checkbox"/>Recibido en su totalidad</label><p className="form-note">Sin esta confirmación la compra queda pendiente de entrega. El pago se registra por separado.</p></>}</>}
  {form==='purchaseReceive'&&<><p className="form-note">{selectedExpense?.supplier} · {selectedExpense?.label}. Indicá solamente lo que llegó; cero no registra una recepción.</p>{selectedLines.map(l=><Field key={l.id} label={`${data.products.find(p=>p.id===l.product)?.name} · pendientes ${receiptPending(data,l)}`} name={'receive-'+l.id} type="number" min="0" step="0.001" value="0"/>)}</>}
  {form==='supplierPay'&&<><p className="form-note">{selectedExpense?.supplier} · {selectedExpense?.label}. Saldo actual {currency(selectedExpense?supplierBalance(data,selectedExpense).balance:0)}. Pagar no recibe stock.</p><Field label="Importe a pagar (ARS)" name="amount" type="number" min="0.01" step="0.01"/><Choice label="Cuenta utilizada" name="account" options={accounts}/><Field label="Referencia del pago" name="reference" required={false}/></>}
 </Editor>}
 <div className="supply-filters"><label className="field"><span>Proveedor</span><Input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><Choice label="Rubro" name="filter-rubro" value={rubro} onChange={setRubro} options={['Todos',...rubros,'Electricidad','Internet','Mantenimiento','Otros servicios','Administración','Otros gastos','Servicios','Insumos']}/><Choice label="Actividad" name="filter-area" value={area} onChange={setArea} options={['Todas','Hotel','Restaurante','Compartido']}/><Choice label="Estado / vencimiento" name="filter-state" value={state} onChange={setState} options={['Todos','Pendiente','Parcialmente pagado','Pagado','Vencido','Próximo a vencer','Sin vencimiento']}/><Choice label="Recepción" name="filter-delivery" value={delivery} onChange={setDelivery} options={['Todas','Pendientes','Recibidas']}/><label className="field"><span>Comprobantes desde</span><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Hasta</span><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 <Table headers={['Proveedor / concepto','Comprobante / rubros','Actividad / tipo','Fecha / vencimiento','Total / pagos / saldo','Estado','Recepción / historial','Acciones']} rows={filtered.map(e=>{const b=supplierBalance(data,e,date),doc=data.purchase_documents.find(d=>d.expense===e.id),ls=data.purchase_lines.filter(l=>l.expense===e.id);return [<span key="e">{e.supplier}<small>{e.label}</small></span>,<span key="doc">{doc?.invoice||'Sin número'}<small>{doc?.type??'Histórico'} · {ls.length?[...new Set(ls.map(l=>l.category))].join(', '):e.category}</small></span>,`${e.area} · ${e.kind}`,<span key="date">{e.date}<small>{e.due||'Vencimiento sin definir'} · {dueLabel(e,b.balance,date)}</small></span>,<span key="money">{currency(e.amount)}<small>Pagos: {currency(b.paid)}</small><b>Saldo: {currency(b.balance)}</b></span>,b.status,<details key="receive"><summary>{doc?.type==='Productos'?ls.some(l=>receiptPending(data,l,date)>0)?'Pendiente / parcial':'Recibido':doc?'Sin stock':'Histórico · sin reinterpretar'}</summary>{ls.map(l=><div key={l.id}>{data.products.find(p=>p.id===l.product)?.name}: {l.qty} · pendientes {receiptPending(data,l,date)} · costo {currency(l.cost)}{data.purchase_receipts.filter(r=>r.line===l.id).map(r=><small key={r.id}>{r.date} · recibido {r.qty} · {r.responsible} {r.observation}</small>)}</div>)}{data.cash_movements.filter(m=>m.ref===e.id&&m.kind==='Pago').map(m=>{const p=data.supplier_payment_details.find(p=>p.cash===m.id);return <div key={m.id}>{m.date} · {m.account} · {currency(-m.amount)}<small>{p?.reference} · {p?.responsible??'Histórico'}</small></div>;})}<p>{doc?.responsible} {doc?.observation}</p></details>,<div key="actions" className="meal-row-actions">{supplierBalance(data,e).balance>0&&<Button variant="outline" onClick={()=>begin('supplierPay',e.id)}>Pagar</Button>}{ls.some(l=>receiptPending(data,l)>0)&&<Button variant="outline" onClick={()=>begin('purchaseReceive',e.id)}>Recibir</Button>}</div>];})}/>
 <History data={data} actions={['purchaseDocument','purchaseReceive','supplierPay']}/></section>;
}
