import type * as schema from '@/db/schema';

export type Booking = typeof schema.bookings.$inferSelect;
export type Product = typeof schema.products.$inferSelect;
export type Sale = typeof schema.sales.$inferSelect;
export type CashMovement = typeof schema.cash.$inferSelect;
export type Expense = typeof schema.expenses.$inferSelect;
export type Rate = typeof schema.rates.$inferSelect;
export type BookingTerms = typeof schema.bookingTerms.$inferSelect;
export type RoomBlock = typeof schema.roomBlocks.$inferSelect;
export type HotelTables = {
  booking_guests: typeof schema.guests.$inferSelect;
  meal_suspensions: typeof schema.suspensions.$inferSelect;
  meal_services: typeof schema.mealServices.$inferSelect;
  meal_plans: typeof schema.mealPlans.$inferSelect;
  rooms: typeof schema.rooms.$inferSelect;
  bookings: Booking;
  products: Product;
  stock_movements: typeof schema.stock.$inferSelect;
  sales: Sale;
  expenses: Expense;
  cash_movements: CashMovement;
  daily_closes: typeof schema.closes.$inferSelect;
  settings: typeof schema.settings.$inferSelect;
  meal_overrides: typeof schema.meals.$inferSelect;
  audit_log: typeof schema.audits.$inferSelect;
  room_rates: Rate;
  booking_terms: BookingTerms;
  room_blocks: RoomBlock;
};
export type HotelData = { [Table in keyof HotelTables]: HotelTables[Table][] };
