import { sqliteTable, text, integer, real, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const rooms=sqliteTable('rooms',{id:integer('id').primaryKey(),type:text('type').notNull(),state:text('state').notNull().default('Limpia'),note:text('note').notNull().default('')});
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),guest:text('guest').notNull(),phone:text('phone').notNull(),room:integer('room').notNull().references(()=>rooms.id),start:text('start').notNull(),end:text('end').notNull(),pax:integer('pax').notNull(),regime:text('regime').notNull(),meal:text('meal').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),source:text('source').notNull(),note:text('note').notNull()},t=>[index('idx_bookings_start').on(t.start)]);
export const slots=sqliteTable('room_nights',{room:integer('room').notNull().references(()=>rooms.id),date:text('date').notNull(),booking:text('booking').notNull().references(()=>bookings.id)},t=>[primaryKey({columns:[t.room,t.date]})]);
export const products=sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),unit:text('unit').notNull(),minimum:real('minimum').notNull(),price:integer('price').notNull(),location:text('location').notNull()});
export const stock=sqliteTable('stock_movements',{id:text('id').primaryKey(),date:text('date').notNull(),product:text('product').notNull().references(()=>products.id),qty:real('qty').notNull(),reason:text('reason').notNull(),ref:text('ref').notNull()},t=>[index('idx_stock_product').on(t.product)]);
export const sales=sqliteTable('sales',{id:text('id').primaryKey(),date:text('date').notNull(),booking:text('booking').references(()=>bookings.id),customer:text('customer').notNull(),label:text('label').notNull(),qty:real('qty').notNull(),amount:integer('amount').notNull(),kind:text('kind').notNull(),service:text('service'),product:text('product'),account:text('account')},t=>[index('idx_sales_booking_date').on(t.booking,t.date)]);
export const expenses=sqliteTable('expenses',{id:text('id').primaryKey(),date:text('date').notNull(),due:text('due').notNull(),supplier:text('supplier').notNull(),label:text('label').notNull(),area:text('area').notNull(),category:text('category').notNull(),amount:integer('amount').notNull(),kind:text('kind').notNull()});
export const cash=sqliteTable('cash_movements',{id:text('id').primaryKey(),date:text('date').notNull(),account:text('account').notNull(),amount:integer('amount').notNull(),area:text('area').notNull(),kind:text('kind').notNull(),ref:text('ref').notNull(),label:text('label').notNull()},t=>[index('idx_cash_ref_kind').on(t.ref,t.kind),index('idx_cash_date').on(t.date)]);
export const closes=sqliteTable('daily_closes',{date:text('date').primaryKey(),expected:integer('expected').notNull(),counted:integer('counted').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),created:text('created').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const meals=sqliteTable('meal_overrides',{booking:text('booking').notNull().references(()=>bookings.id),date:text('date').notNull(),meal:text('meal').notNull()},t=>[primaryKey({columns:[t.booking,t.date]})]);
export const audits=sqliteTable('audit_log',{id:text('id').primaryKey(),created:text('created').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),detail:text('detail').notNull()});
export const requests=sqliteTable('operation_requests',{key:text('key').primaryKey(),fingerprint:text('fingerprint').notNull(),created:text('created').notNull()});
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),passwordVersion:text('password_version').notNull(),expires:integer('expires').notNull()},t=>[index('idx_auth_sessions_expires').on(t.expires)]);
export const authAttempts=sqliteTable('auth_attempts',{id:text('id').primaryKey(),created:integer('created').notNull()},t=>[index('idx_auth_attempts_created').on(t.created)]);
export const rates=sqliteTable('room_rates',{
 id:text('id').primaryKey(),type:text('type').notNull(),regime:text('regime').notNull(),start:text('start').notNull(),end:text('end').notNull(),amount:integer('amount').notNull(),version:integer('version').notNull().default(0),responsible:text('responsible').notNull(),note:text('note').notNull().default(''),
},t=>[index('idx_rates_period').on(t.type,t.regime,t.start,t.end)]);
export const bookingTerms=sqliteTable('booking_terms',{
 booking:text('booking').primaryKey().references(()=>bookings.id),base_amount:integer('base_amount').notNull(),tariff_total:integer('tariff_total'),discount_amount:integer('discount_amount').notNull().default(0),discount_type:text('discount_type').notNull().default('Ninguno'),discount_value:integer('discount_value').notNull().default(0),price_mode:text('price_mode').notNull().default('Historico'),snapshot:text('snapshot').notNull().default('[]'),payment_condition:text('payment_condition').notNull().default('Sin especificar'),benefit:text('benefit').notNull().default('Habitual'),reason:text('reason').notNull().default(''),responsible:text('responsible').notNull().default(''),observation:text('observation').notNull().default(''),barter_agreement:text('barter_agreement').notNull().default(''),barter_status:text('barter_status').notNull().default('No corresponde'),version:integer('version').notNull().default(0),
});
export const roomBlocks=sqliteTable('room_blocks',{
 id:text('id').primaryKey(),room:integer('room').notNull().references(()=>rooms.id),start:text('start').notNull(),end:text('end').notNull(),reason:text('reason').notNull(),responsible:text('responsible').notNull(),active:integer('active').notNull().default(1),
},t=>[index('idx_blocks_room_period').on(t.room,t.start,t.end)]);
