import { sqliteTable, text, integer, real, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const rooms=sqliteTable('rooms',{id:integer('id').primaryKey(),type:text('type').notNull(),state:text('state').notNull().default('Limpia'),note:text('note').notNull().default('')});
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),guest:text('guest').notNull(),phone:text('phone').notNull(),room:integer('room').notNull().references(()=>rooms.id),start:text('start').notNull(),end:text('end').notNull(),pax:integer('pax').notNull(),regime:text('regime').notNull(),meal:text('meal').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),source:text('source').notNull(),note:text('note').notNull()},t=>[index('idx_bookings_start').on(t.start)]);
export const slots=sqliteTable('room_nights',{room:integer('room').notNull().references(()=>rooms.id),date:text('date').notNull(),booking:text('booking').notNull().references(()=>bookings.id)},t=>[primaryKey({columns:[t.room,t.date]})]);
export const products=sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),unit:text('unit').notNull(),minimum:real('minimum').notNull(),price:integer('price').notNull(),location:text('location').notNull()});
export const stock=sqliteTable('stock_movements',{id:text('id').primaryKey(),date:text('date').notNull(),product:text('product').notNull().references(()=>products.id),qty:real('qty').notNull(),reason:text('reason').notNull(),ref:text('ref').notNull()},t=>[index('idx_stock_product').on(t.product)]);
export const sales=sqliteTable('sales',{id:text('id').primaryKey(),date:text('date').notNull(),booking:text('booking').references(()=>bookings.id),customer:text('customer').notNull(),label:text('label').notNull(),qty:real('qty').notNull(),amount:integer('amount').notNull(),kind:text('kind').notNull(),service:text('service'),product:text('product'),account:text('account')},t=>[index('idx_sales_booking_date').on(t.booking,t.date)]);
export const expenses=sqliteTable('expenses',{id:text('id').primaryKey(),date:text('date').notNull(),due:text('due').notNull(),supplier:text('supplier').notNull(),label:text('label').notNull(),area:text('area').notNull(),category:text('category').notNull(),amount:integer('amount').notNull(),kind:text('kind').notNull()});
export const cash=sqliteTable('cash_movements',{id:text('id').primaryKey(),date:text('date').notNull(),account:text('account').notNull(),amount:integer('amount').notNull(),area:text('area').notNull(),kind:text('kind').notNull(),ref:text('ref').notNull(),label:text('label').notNull()},t=>[index('idx_cash_ref_kind').on(t.ref,t.kind),index('idx_cash_date').on(t.date)]);
export const closes=sqliteTable('daily_closes',{date:text('date').primaryKey(),expected:integer('expected').notNull(),counted:integer('counted').notNull(),note:text('note').notNull(),actor:text('actor').notNull(),created:text('created').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const meals=sqliteTable('meal_overrides',{booking:text('booking').notNull().references(()=>bookings.id),date:text('date').notNull(),meal:text('meal').notNull()},t=>[primaryKey({columns:[t.booking,t.date]})]);
export const audits=sqliteTable('audit_log',{id:text('id').primaryKey(),created:text('created').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),detail:text('detail').notNull(),actor_id:text('actor_id').references(()=>users.id)});
export const requests=sqliteTable('operation_requests',{key:text('key').primaryKey(),fingerprint:text('fingerprint').notNull(),created:text('created').notNull(),user_id:text('user_id').references(()=>users.id)});
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),passwordVersion:text('password_version').notNull(),expires:integer('expires').notNull(),user_id:text('user_id').references(()=>users.id)},t=>[index('idx_auth_sessions_expires').on(t.expires)]);
export const authAttempts=sqliteTable('auth_attempts',{id:text('id').primaryKey(),created:integer('created').notNull()},t=>[index('idx_auth_attempts_created').on(t.created)]);
export const rates=sqliteTable('room_rates',{
 id:text('id').primaryKey(),type:text('type').notNull(),regime:text('regime').notNull(),start:text('start').notNull(),end:text('end').notNull(),amount:integer('amount').notNull(),version:integer('version').notNull().default(0),responsible:text('responsible').notNull(),note:text('note').notNull().default(''),
},t=>[index('idx_rates_period').on(t.type,t.regime,t.start,t.end)]);
export const bookingTerms=sqliteTable('booking_terms',{
 booking:text('booking').primaryKey().references(()=>bookings.id),base_amount:integer('base_amount').notNull(),tariff_total:integer('tariff_total'),discount_amount:integer('discount_amount').notNull().default(0),discount_type:text('discount_type').notNull().default('Ninguno'),discount_value:integer('discount_value').notNull().default(0),price_mode:text('price_mode').notNull().default('Historico'),snapshot:text('snapshot').notNull().default('[]'),payment_condition:text('payment_condition').notNull().default('Sin especificar'),benefit:text('benefit').notNull().default('Habitual'),reason:text('reason').notNull().default(''),responsible:text('responsible').notNull().default(''),observation:text('observation').notNull().default(''),barter_agreement:text('barter_agreement').notNull().default(''),barter_status:text('barter_status').notNull().default('No corresponde'),version:integer('version').notNull().default(0),
});
export const roomBlocks=sqliteTable('room_blocks',{
 id:text('id').primaryKey(),room:integer('room').notNull().references(()=>rooms.id),start:text('start').notNull(),end:text('end').notNull(),reason:text('reason').notNull(),responsible:text('responsible').notNull(),active:integer('active').notNull().default(1),
},t=>[index('idx_blocks_room_period').on(t.room,t.start,t.end)]);
export const guests=sqliteTable('booking_guests',{id:text('id').primaryKey(),booking:text('booking').notNull().references(()=>bookings.id),position:integer('position').notNull(),name:text('name').notNull().default(''),restrictions:text('restrictions').notNull().default(''),preferences:text('preferences').notNull().default(''),observation:text('observation').notNull().default(''),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_guest_position').on(t.booking,t.position)]);
export const suspensions=sqliteTable('meal_suspensions',{guest:text('guest').notNull().references(()=>guests.id),date:text('date').notNull(),service:text('service').notNull(),active:integer('active').notNull(),reason:text('reason').notNull(),observation:text('observation').notNull().default(''),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[primaryKey({columns:[t.guest,t.date,t.service]})]);
export const mealServices=sqliteTable('meal_services',{guest:text('guest').notNull().references(()=>guests.id),date:text('date').notNull(),service:text('service').notNull(),sale:text('sale').notNull().references(()=>sales.id)},t=>[primaryKey({columns:[t.guest,t.date,t.service]})]);
export const mealPlans=sqliteTable('meal_plans',{id:text('id').primaryKey(),guest:text('guest').references(()=>guests.id),customer:text('customer').notNull(),date:text('date').notNull(),service:text('service').notNull(),qty:integer('qty').notNull(),observation:text('observation').notNull().default(''),status:text('status').notNull().default('Pendiente'),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_person_meal_plan').on(t.guest,t.date,t.service).where(sql.raw("guest IS NOT NULL AND status<>'Cancelada'"))]);
export const beverageAccounts=sqliteTable('beverage_accounts',{id:text('id').primaryKey(),table_name:text('table_name').notNull(),opened_at:text('opened_at').notNull(),responsible:text('responsible').notNull()});
export const beverageDispatches=sqliteTable('beverage_dispatches',{sale:text('sale').primaryKey().references(()=>sales.id),time:text('time').notNull(),destination:text('destination').notNull(),table_account:text('table_account').references(()=>beverageAccounts.id),mode:text('mode').notNull(),price:integer('price').notNull(),reason:text('reason').notNull(),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const beverageSettlements=sqliteTable('beverage_settlements',{table_account:text('table_account').primaryKey().references(()=>beverageAccounts.id),date:text('date').notNull(),method:text('method').notNull(),account:text('account'),booking:text('booking').references(()=>bookings.id),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const beverageTransfers=sqliteTable('beverage_transfers',{dispatch:text('dispatch').primaryKey().references(()=>beverageDispatches.sale),sale:text('sale').notNull().references(()=>sales.id)},t=>[uniqueIndex('idx_beverage_transfer_sale').on(t.sale)]);
export const beverageReturns=sqliteTable('beverage_returns',{id:text('id').primaryKey(),dispatch:text('dispatch').notNull().references(()=>beverageDispatches.sale),date:text('date').notNull(),qty:real('qty').notNull(),reason:text('reason').notNull(),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const beverageCorrections=sqliteTable('beverage_corrections',{dispatch:text('dispatch').primaryKey().references(()=>beverageDispatches.sale),sale:text('sale').notNull().references(()=>sales.id),date:text('date').notNull(),reason:text('reason').notNull(),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const purchaseDocuments=sqliteTable('purchase_documents',{expense:text('expense').primaryKey().references(()=>expenses.id),invoice:text('invoice').notNull(),type:text('type').notNull(),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const purchaseLines=sqliteTable('purchase_lines',{id:text('id').primaryKey(),expense:text('expense').notNull().references(()=>purchaseDocuments.expense),product:text('product').notNull().references(()=>products.id),category:text('category').notNull(),qty:real('qty').notNull(),cost:integer('cost').notNull(),amount:integer('amount').notNull()},t=>[index('idx_purchase_lines_expense').on(t.expense)]);
export const purchaseReceipts=sqliteTable('purchase_receipts',{id:text('id').primaryKey(),line:text('line').notNull().references(()=>purchaseLines.id),date:text('date').notNull(),qty:real('qty').notNull(),responsible:text('responsible').notNull(),observation:text('observation').notNull()});
export const supplierPaymentDetails=sqliteTable('supplier_payment_details',{cash:text('cash').primaryKey().references(()=>cash.id),reference:text('reference').notNull(),responsible:text('responsible').notNull()});
export const suppliers=sqliteTable('suppliers',{id:text('id').primaryKey(),name:text('name').notNull(),contact:text('contact').notNull(),rubros:text('rubros').notNull(),observation:text('observation').notNull(),frequency:text('frequency').notNull(),schedule:text('schedule').notNull(),lead_days:integer('lead_days'),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)});
export const deliveries=sqliteTable('supplier_deliveries',{id:text('id').primaryKey(),supplier:text('supplier').notNull().references(()=>suppliers.id),source_key:text('source_key'),original_date:text('original_date'),date:text('date'),deadline:text('deadline'),status:text('status').notNull(),expense:text('expense').references(()=>expenses.id),observation:text('observation').notNull(),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_delivery_source').on(t.source_key),index('idx_delivery_date').on(t.date)]);
export const menuPlans=sqliteTable('menu_plans',{id:text('id').primaryKey(),date:text('date').notNull(),service:text('service').notNull(),dishes:text('dishes').notNull(),alternatives:text('alternatives').notNull(),conditions:text('conditions').notNull(),observation:text('observation').notNull(),status:text('status').notNull(),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_menu_day_service').on(t.date,t.service)]);
export const menuActuals=sqliteTable('menu_actuals',{id:text('id').primaryKey(),plan:text('plan').notNull().references(()=>menuPlans.id),dishes:text('dishes').notNull(),alternatives:text('alternatives').notNull(),conditions:text('conditions').notNull(),observation:text('observation').notNull(),planned_snapshot:text('planned_snapshot').notNull(),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_actual_menu_plan').on(t.plan)]);
export const employees=sqliteTable('employees',{id:text('id').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),contact:text('contact').notNull(),active:integer('active').notNull(),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)});
export const staffEvents=sqliteTable('staff_events',{id:text('id').primaryKey(),employee:text('employee').notNull().references(()=>employees.id),kind:text('kind').notNull(),start:text('start').notNull(),end:text('end').notNull(),status:text('status').notNull(),attendance:text('attendance').notNull(),actual_start:text('actual_start'),actual_end:text('actual_end'),conflict_ack:integer('conflict_ack').notNull(),observation:text('observation').notNull(),responsible:text('responsible').notNull(),version:integer('version').notNull().default(0)},t=>[index('idx_staff_employee_period').on(t.employee,t.start,t.end)]);
export const staffReports=sqliteTable('staff_reports',{id:text('id').primaryKey(),employee:text('employee').notNull().references(()=>employees.id),event:text('event').references(()=>staffEvents.id),date:text('date').notNull(),author:text('author').notNull(),type:text('type').notNull(),description:text('description').notNull(),status:text('status').notNull(),followup:text('followup').notNull(),version:integer('version').notNull().default(0)});
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),active:integer('active').notNull().default(1),roles:text('roles').notNull(),password_hash:text('password_hash').notNull(),version:integer('version').notNull().default(0)},t=>[uniqueIndex('idx_user_email').on(t.email)]);
export const roles=sqliteTable('roles',{id:text('id').primaryKey(),name:text('name').notNull(),permissions:text('permissions').notNull(),version:integer('version').notNull().default(0)});
export const accessState=sqliteTable('access_state',{id:integer('id').primaryKey(),revision:integer('revision').notNull()});
export const accessChecks=sqliteTable('access_checks',{id:text('id').primaryKey(),user_id:text('user_id').notNull().references(()=>users.id),session_hash:text('session_hash').notNull(),revision:integer('revision').notNull()});
