import { database } from '@/lib/hotel-db';
import { requireSession, checkOrigin } from '@/lib/hotel-auth';
import { z } from 'zod';
export const dynamic='force-dynamic';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Fecha inválida');
const str=z.string().trim().min(1).max(240), money=z.coerce.number().finite().min(0).max(100000000), qty=z.coerce.number().finite().positive().max(100000);
const account=z.enum(['Efectivo','Banco','Billetera']);const area=z.enum(['Hotel','Restaurante','Compartido']);
const schemas:any={
 booking:z.object({guest:str,phone:z.string().max(80).default(''),room:z.coerce.number().int(),start:date,end:date,pax:z.coerce.number().int().min(1).max(2),regime:z.enum(['Desayuno','MP','PC']),meal:z.enum(['Cena','Almuerzo']),amount:money,source:str,note:z.string().max(1000).default('')}),
 status:z.object({id:str,status:z.enum(['Confirmada','Alojado','Finalizada','Cancelada'])}),
 room:z.object({room:z.coerce.number().int(),state:z.enum(['Limpia','Pendiente de limpieza','Fuera de servicio']),note:z.string().max(1000).default('')}),
 sale:z.object({date,booking:z.string().default(''),customer:str,kind:z.enum(['Comida','Bebida','Incluida','Cortesía','Interno']),product:z.string().default(''),label:str,service:z.enum(['Desayuno','Almuerzo','Cena']).default('Cena'),qty,price:money,account,charge:z.boolean().default(false)}),
 payment:z.object({date,booking:str,amount:money.refine(v=>v>0),account}),
 expense:z.object({date,due:date,supplier:str,label:str,area,category:str,amount:money.refine(v=>v>0),kind:z.enum(['Fijo','Variable']),paid:z.boolean(),account}),
 payExpense:z.object({date,id:str,amount:money.refine(v=>v>0),account}),
 stock:z.object({date,product:str,qty:z.coerce.number().finite().min(-100000).max(100000),reason:z.enum(['Entrega a cocina','Entrega a limpieza','Merma','Rotura / pérdida','Conteo físico','Consumo interno'])}),
 purchase:z.object({date,due:date,supplier:str,product:str,qty,cost:money.refine(v=>v>0),paid:z.boolean(),account}),
 product:z.object({name:str,category:z.enum(['Bebidas','Alimentos','Limpieza y amenities','Reutilizables']),unit:z.enum(['un','kg','l']),minimum:money,price:money,location:str}),
 close:z.object({date,counted:money,note:z.string().max(1000).default('')}),
 transfer:z.object({date,from:account,to:account,amount:money.refine(v=>v>0)}),
 movement:z.object({date,account,amount:money.refine(v=>v>0),kind:z.enum(['Aporte de socios','Retiro de socios']),label:str}),
 settings:z.object({mealPrice:money}),
 meal:z.object({booking:str,date,meal:z.enum(['Cena','Almuerzo'])})
};
const cents=(n:number)=>Math.round(n*100);const id=()=>crypto.randomUUID();
function nights(start:string,end:string){let dates=[];for(let d=new Date(start);d<new Date(end);d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));if(!dates.length||dates.length>365)throw new Error('La salida debe ser posterior a la llegada, hasta 365 noches.');return dates;}
async function seed(db:any){const exists=await db.prepare("SELECT value FROM settings WHERE key='initialized'").first();if(exists)return;
const statements:any[]=[];const add=(sql:string,...v:any[])=>statements.push(db.prepare(sql).bind(...v));
[2,3,4,5,6,7,8,9,10,11,12,14,18,20,22,24,25].forEach((n,i)=>add('INSERT OR IGNORE INTO rooms (id,type,state,note) VALUES (?,?,?,?)',n,i===16?'Single':'Doble',n===22?'Pendiente de limpieza':n===24?'Fuera de servicio':'Limpia',n===24?'Revisión de calefacción':''));
const demo=[['demo-1','Lucía Fernández',7,'2026-09-30','2026-10-05',2,'MP','Cena',30000000,'Alojado'],['demo-2','Martín Acosta',9,'2026-10-01','2026-10-04',2,'PC','Cena',25500000,'Alojado'],['demo-3','Valentina Ruiz',3,'2026-10-02','2026-10-06',2,'Desayuno','Cena',22000000,'Confirmada'],['demo-4','Diego Molina',25,'2026-10-03','2026-10-07',1,'MP','Cena',18000000,'Confirmada'],['demo-5','Camila Torres',12,'2026-10-05','2026-10-10',2,'PC','Cena',42500000,'Confirmada']];
for(const b of demo){add("INSERT OR IGNORE INTO bookings (id,guest,room,start,end,pax,regime,meal,amount,status,phone,source,note) VALUES (?,?,?,?,?,?,?,?,?,?,'','Directa','Datos ficticios')",...b);for(const d of nights(b[3] as string,b[4] as string))add('INSERT OR IGNORE INTO room_nights (room,date,booking) VALUES (?,?,?)',b[2],d,b[0]);}
const ps=[['agua','Agua mineral 500 ml','Bebidas','un',24,250000,'Restaurante',42],['vino','Vino tinto 750 ml','Bebidas','un',6,1200000,'Restaurante',5],['carne','Carne vacuna','Alimentos','kg',10,0,'Cocina',18],['harina','Harina','Alimentos','kg',8,0,'Cocina',6],['detergente','Detergente','Limpieza y amenities','l',5,0,'Depósito',12],['toallas','Toallas de baño','Reutilizables','un',40,0,'Lavandería',56]];
for(const p of ps){add('INSERT OR IGNORE INTO products (id,name,category,unit,minimum,price,location) VALUES (?,?,?,?,?,?,?)',...p.slice(0,7));add("INSERT OR IGNORE INTO stock_movements VALUES (?, '2026-10-01', ?, ?, 'Saldo inicial de ejemplo', '')",'seed-'+p[0],p[0],p[7]);}
add("INSERT OR IGNORE INTO cash_movements VALUES ('opening-cash','2026-10-01','Efectivo',12000000,'Compartido','Saldo inicial','','Apertura de ejemplo')");add("INSERT OR IGNORE INTO cash_movements VALUES ('opening-bank','2026-10-01','Banco',48000000,'Compartido','Saldo inicial','','Apertura de ejemplo')");
add("INSERT OR IGNORE INTO cash_movements VALUES ('deposit-1','2026-10-01','Banco',10000000,'Hotel','Cobro','demo-1','Seña · Lucía Fernández')");
add("INSERT OR IGNORE INTO expenses VALUES ('expense-1','2026-10-01','2026-10-05','Proveedor de energía','Electricidad','Compartido','Servicios',8500000,'Fijo')");
add("INSERT OR IGNORE INTO settings VALUES ('mealPrice','0')");add("INSERT OR IGNORE INTO settings VALUES ('initialized','1')");await db.batch(statements);}
export async function GET(req:Request){const rejected=await requireSession(req);if(rejected)return rejected;try{const db=database();await seed(db);const tables=['rooms','bookings','products','stock_movements','sales','expenses','cash_movements','daily_closes','settings','meal_overrides','audit_log'];const rs=await db.batch(tables.map(t=>db.prepare(`SELECT * FROM ${t}`)));return Response.json(Object.fromEntries(tables.map((t,i)=>[t,rs[i].results])),{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'No se pudieron cargar los registros. Intentá nuevamente.'},{status:503});}}
export async function POST(req:Request){
const rejected=await requireSession(req);if(rejected)return rejected;const originError=checkOrigin(req);if(originError)return originError;
let requestKey:string|undefined, fingerprint:string|undefined, requestDb:D1Database|undefined;
try{const body:any=await req.json();if(!Object.hasOwn(schemas,body.action))throw new Error('Acción inválida');if(body.action==='sale'){if(body.data.booking==='external')body.data.booking='';if(body.data.product==='none')body.data.product='';}const d=schemas[body.action].parse(body.data);const db=database();requestDb=db;await seed(db);
requestKey=z.string().uuid().parse(req.headers.get('Idempotency-Key'));
fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({action:body.action,data:d}))))).map(v=>v.toString(16).padStart(2,'0')).join('');
const previous=await db.prepare('SELECT fingerprint FROM operation_requests WHERE key=?').bind(requestKey).first<{fingerprint:string}>();
if(previous)return Response.json(previous.fingerprint===fingerprint?{ok:true}:{error:'La clave de operacion ya se uso con otros datos.'},{status:previous.fingerprint===fingerprint?200:409});
const actor='Acceso compartido de prueba';const stmts:any[]=[];const add=(sql:string,...v:any[])=>stmts.push(db.prepare(sql).bind(...v));const row=async(t:string,key:string,val:any)=>db.prepare(`SELECT * FROM ${t} WHERE ${key}=?`).bind(val).first();
add('INSERT INTO operation_requests (key,fingerprint,created) VALUES (?,?,?)',requestKey,fingerprint,new Date().toISOString());
if(d.date&&['sale','payment','expense','payExpense','stock','purchase','transfer','movement','meal'].includes(body.action)){if(await db.prepare('SELECT date FROM daily_closes WHERE date>=? LIMIT 1').bind(d.date).first())throw new Error('Ese día ya está cerrado. Usá una fecha posterior al último cierre.');}
const cash=(date:string,acc:string,amount:number,ar:string,kind:string,ref:string,label:string)=>add('INSERT INTO cash_movements VALUES (?,?,?,?,?,?,?,?)',id(),date,acc,amount,ar,kind,ref,label);
if(body.action==='booking'){const dates=nights(d.start,d.end), room:any=await row('rooms','id',d.room);if(!room||room.state==='Fuera de servicio')throw new Error('Habitación no disponible.');if(room.type==='Single'&&d.pax>1)throw new Error('Una habitación single admite una persona.');const key=id();add('INSERT INTO bookings VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',key,d.guest,d.phone,d.room,d.start,d.end,d.pax,d.regime,d.meal,cents(d.amount),'Confirmada',d.source,d.note);for(const day of dates)add('INSERT INTO room_nights VALUES (?,?,?)',d.room,day,key);}
if(body.action==='status'){const b:any=await row('bookings','id',d.id);if(!b)throw new Error('Reserva inexistente');if(['Cancelada','Finalizada'].includes(b.status))throw new Error('La estadía ya está cerrada.');if(d.status==='Finalizada'){const s:any=await db.prepare("SELECT COALESCE(SUM(amount),0) amount FROM sales WHERE booking=?").bind(d.id).first();const p:any=await db.prepare("SELECT COALESCE(SUM(amount),0) amount FROM cash_movements WHERE ref=? AND kind='Cobro'").bind(d.id).first();if(b.amount+s.amount>p.amount)throw new Error('Registrá el cobro pendiente antes de finalizar.');}if(d.status==='Cancelada'){const p:any=await db.prepare("SELECT COUNT(*) n FROM cash_movements WHERE ref=?").bind(d.id).first();const s:any=await db.prepare('SELECT COUNT(*) n FROM sales WHERE booking=?').bind(d.id).first();if(p.n||s.n)throw new Error('La reserva tiene movimientos. La devolución o regularización requiere revisión; no se puede cancelar aquí.');add('DELETE FROM room_nights WHERE booking=?',d.id);}add('UPDATE bookings SET status=? WHERE id=?',d.status,d.id);if(d.status==='Finalizada')add("UPDATE rooms SET state='Pendiente de limpieza' WHERE id=?",b.room);}
if(body.action==='room'){if(!await row('rooms','id',d.room))throw new Error('Habitación inexistente');add('UPDATE rooms SET state=?,note=? WHERE id=?',d.state,d.note,d.room);}
if(body.action==='sale'){let booking:any=null;if(d.booking){booking=await row('bookings','id',d.booking);if(!booking||['Cancelada','Finalizada'].includes(booking.status))throw new Error('Elegí una estadía activa.');}if(d.charge&&!booking)throw new Error('Seleccioná la estadía para el cargo.');if(d.kind==='Incluida'&&!booking)throw new Error('Una comida incluida necesita una estadía.');if(booking&&(d.date<booking.start||d.date>booking.end))throw new Error('El consumo debe corresponder a las fechas de la estadía.');if(d.kind==='Bebida'&&!d.product)throw new Error('Seleccioná una bebida de stock.');if(d.kind==='Incluida'){if(d.product||!Number.isInteger(d.qty))throw new Error('Una comida incluida requiere personas enteras y no admite bebidas.');d.label=d.service;if(d.date===booking.end)throw new Error('Las comidas del día de salida necesitan revisión; registralas aparte por ahora.');const choice:any=await db.prepare('SELECT meal FROM meal_overrides WHERE booking=? AND date=?').bind(d.booking,d.date).first();const chosen=choice?.meal||booking.meal;if(d.service!=='Desayuno'&&booking.regime==='Desayuno'||booking.regime==='MP'&&d.service!=='Desayuno'&&d.service!==chosen)throw new Error('Esa comida no está incluida en el régimen de la estadía.');const served:any=await db.prepare("SELECT COALESCE(SUM(qty),0) n FROM sales WHERE booking=? AND date=? AND (service=? OR service IS NULL OR (service<>'Desayuno' AND ?<>'Desayuno' AND ?='MP')) AND kind='Incluida'").bind(d.booking,d.date,d.service,d.service,booking.regime).first();if(served.n+d.qty>booking.pax)throw new Error('La cantidad supera las comidas incluidas para ese día.');} const total=['Incluida','Cortesía','Interno'].includes(d.kind)?0:cents(d.price*d.qty);if(!total&&['Comida','Bebida'].includes(d.kind))throw new Error('Definí un precio mayor a cero.');const key=id();if(d.product){const p:any=await row('products','id',d.product);if(!p||p.category!=='Bebidas')throw new Error('Elegí una bebida del catálogo.');const st:any=await db.prepare('SELECT COALESCE(SUM(qty),0) n FROM stock_movements WHERE product=?').bind(d.product).first();if(st.n<d.qty)throw new Error('Stock insuficiente.');add("INSERT INTO stock_movements VALUES (?,?,?,?,'Venta / consumo',?)",id(),d.date,d.product,-d.qty,key);}add('INSERT INTO sales (id,date,booking,customer,label,qty,amount,kind,product,account,service) VALUES (?,?,?,?,?,?,?,?,?,?,?)',key,d.date,d.charge||d.kind==='Incluida'?d.booking:null,booking?booking.guest:d.customer,d.label,d.qty,total,d.kind,d.product||null,d.charge||!total?null:d.account,d.kind==='Incluida'?d.service:null);if(total&&!d.charge)cash(d.date,d.account,total,'Restaurante','Venta',key,d.label);}
if(body.action==='payment'){const b:any=await row('bookings','id',d.booking);if(!b||['Cancelada','Finalizada'].includes(b.status))throw new Error('Seleccioná una estadía activa.');const s:any=await db.prepare('SELECT COALESCE(SUM(amount),0) n FROM sales WHERE booking=?').bind(d.booking).first();const p:any=await db.prepare("SELECT COALESCE(SUM(amount),0) n FROM cash_movements WHERE ref=? AND kind='Cobro'").bind(d.booking).first();if(cents(d.amount)>b.amount+s.n-p.n)throw new Error('El cobro supera el saldo pendiente.');cash(d.date,d.account,cents(d.amount),'Hotel','Cobro',d.booking,'Cobro · '+b.guest);}
if(body.action==='expense'){const key=id();add('INSERT INTO expenses VALUES (?,?,?,?,?,?,?,?,?)',key,d.date,d.due,d.supplier,d.label,d.area,d.category,cents(d.amount),d.kind);if(d.paid)cash(d.date,d.account,-cents(d.amount),d.area,'Pago',key,d.label);}
if(body.action==='payExpense'){const e:any=await row('expenses','id',d.id);if(!e)throw new Error('Gasto inexistente.');const p:any=await db.prepare("SELECT COALESCE(-SUM(amount),0) n FROM cash_movements WHERE ref=? AND kind='Pago'").bind(d.id).first();if(cents(d.amount)>e.amount-p.n)throw new Error('El pago supera lo adeudado.');cash(d.date,d.account,-cents(d.amount),e.area,'Pago',d.id,e.label);}
if(body.action==='stock'){const p:any=await row('products','id',d.product);if(!p)throw new Error('Producto inexistente');const s:any=await db.prepare('SELECT COALESCE(SUM(qty),0) n FROM stock_movements WHERE product=?').bind(d.product).first();const delta=d.reason==='Conteo físico'?d.qty-s.n:-Math.abs(d.qty);if(d.reason==='Conteo físico'&&d.qty<0)throw new Error('El conteo no puede ser negativo');if(s.n+delta<0)throw new Error('La salida supera el stock.');if(delta===0)throw new Error('No hay una diferencia para registrar.');add('INSERT INTO stock_movements VALUES (?,?,?,?,?,?)',id(),d.date,d.product,delta,d.reason,'');}
if(body.action==='purchase'){const p:any=await row('products','id',d.product);if(!p)throw new Error('Producto inexistente');const key=id(),ar=p.category==='Bebidas'||p.category==='Alimentos'?'Restaurante':'Compartido';add('INSERT INTO expenses VALUES (?,?,?,?,?,?,?,?,?)',key,d.date,d.due,d.supplier,'Compra · '+p.name,ar,'Insumos',cents(d.qty*d.cost),'Variable');add('INSERT INTO stock_movements VALUES (?,?,?,?,?,?)',id(),d.date,d.product,d.qty,'Compra',key);if(d.paid)cash(d.date,d.account,-cents(d.qty*d.cost),ar,'Pago',key,'Compra · '+p.name);}
if(body.action==='product')add('INSERT INTO products VALUES (?,?,?,?,?,?,?)',id(),d.name,d.category,d.unit,d.minimum,cents(d.price),d.location);
if(body.action==='close'){
 // SELECT and triggers execute in the same batch transaction as the request and audit.
 add("INSERT INTO daily_closes (date,expected,counted,note,actor,created) SELECT ?,COALESCE(SUM(amount),0),?,?,?,? FROM cash_movements WHERE account='Efectivo' AND date<=?",d.date,cents(d.counted),d.note,actor,new Date().toISOString(),d.date);
}
if(body.action==='transfer'){if(d.from===d.to)throw new Error('Las cuentas deben ser distintas');const key=id();cash(d.date,d.from,-cents(d.amount),'Compartido','Transferencia',key,'Transferencia a '+d.to);cash(d.date,d.to,cents(d.amount),'Compartido','Transferencia',key,'Transferencia desde '+d.from);}
if(body.action==='movement')cash(d.date,d.account,cents(d.amount)*(d.kind==='Retiro de socios'?-1:1),'Compartido',d.kind,'',d.label);
if(body.action==='settings')add("UPDATE settings SET value=? WHERE key='mealPrice'",String(cents(d.mealPrice)));
if(body.action==='meal'){const b:any=await row('bookings','id',d.booking);if(!b||['Cancelada','Finalizada'].includes(b.status)||b.regime!=='MP'||d.date<b.start||d.date>=b.end)throw new Error('Elegí un día de una estadía con media pensión.');add('INSERT INTO meal_overrides VALUES (?,?,?) ON CONFLICT(booking,date) DO UPDATE SET meal=excluded.meal',d.booking,d.date,d.meal);}
add('INSERT INTO audit_log VALUES (?,?,?,?,?)',id(),new Date().toISOString(),actor,body.action,JSON.stringify(d));await db.batch(stmts);return Response.json({ok:true});}catch(e:any){
 // A concurrent identical request can win after our first lookup or validation.
 if(requestDb&&requestKey&&fingerprint){
  const saved=await requestDb.prepare('SELECT fingerprint FROM operation_requests WHERE key=?').bind(requestKey).first<{fingerprint:string}>();
  if(saved)return Response.json(saved.fingerprint===fingerprint?{ok:true}:{error:'La clave de operacion ya se uso con otros datos.'},{status:saved.fingerprint===fingerprint?200:409});
 }
 console.error(e);let msg=e instanceof z.ZodError?'Revisá los campos y las fechas del formulario.':e.message||'No se pudo guardar.';if(/UNIQUE constraint.*room_nights/.test(msg))msg='La habitación ya tiene una reserva en esas fechas.';else if(/UNIQUE constraint/.test(msg))msg='Ese registro ya existe.';else if(/Ese dia ya esta cerrado/.test(msg))msg='Ese día ya está cerrado. Usá una fecha posterior al último cierre.';else if(/Ya se sirvio otra comida/.test(msg))msg='Ya se sirvió otra comida incluida ese día; no se puede cambiar la elección.';else if(/comidas incluidas para ese dia/.test(msg))msg='La cantidad supera las comidas incluidas para ese día.';else if(/Explica la diferencia de caja/.test(msg))msg='Explicá la diferencia de caja.';else if(/La fecha debe ser posterior al ultimo cierre/.test(msg))msg='La fecha debe ser posterior al último cierre.';else if(/Esa comida no esta incluida/.test(msg))msg='Esa comida no está incluida en la estadía.';else if(/D1_|SQLITE_|constraint/i.test(msg))msg='No se pudo guardar. Revisá la disponibilidad e intentá nuevamente.';return Response.json({error:msg},{status:400});}}
