'use client';

import { dispatchStatus,tableTotal } from '@/lib/hotel-supply-view';
import { currency } from '@/lib/hotel-view';
import { ActionButton as Button,useIdentity } from '@/modules/access/context';
import { can } from '@/modules/access/permissions';
import { accounts,Choice,Editor,Field,History,Props,Table } from '@/modules/shared/supply-ui';
import { useState } from 'react';
export function Beverages({data,date,onSave}:Props){
 const identity=useIdentity();
 const [form,setForm]=useState(''),[selected,setSelected]=useState(''),[destination,setDestination]=useState('Mesa'),[mode,setMode]=useState('Pendiente'),[product,setProduct]=useState(data.products.find(p=>p.category==='Bebidas')?.id??'');
 const open=data.beverage_accounts.filter(a=>!data.beverage_settlements.some(s=>s.table_account===a.id));
 const bookings=data.bookings.filter(b=>['Confirmada','Alojado'].includes(b.status));
 const close=()=>setForm('');const begin=(f:string,id='')=>{setSelected(id);setForm(f);};
 const target=data.sales.find(s=>s.id===selected);
 const returned=(id:string)=>data.beverage_returns.filter(r=>r.dispatch===id).reduce((n,r)=>n+r.qty,0);
 return <section className="panel spaced"><div className="panel-heading"><div><h2>Bebidas y cuentas de mesa</h2><p>Destino físico y cobro se registran por separado.</p></div><div className="meal-row-actions"><Button variant="outline" onClick={()=>begin('beverageAccount')} permission="restaurant.create">Abrir cuenta de mesa</Button><Button onClick={()=>begin('beverageDispatch')} permission="restaurant.create">Despachar bebida</Button></div></div>
 {form&&<Editor key={form+selected} title={form==='beverageAccount'?'Abrir una cuenta nueva':form==='beverageDispatch'?'Registrar despacho':form==='beverageSettle'?'Cerrar cuenta de mesa':form==='beverageReturn'?'Devolución física al stock':'Corregir un despacho'} date={date} onCancel={close} onSubmit={v=>onSave(form,form==='beverageDispatch'?{...v,tableAccount:destination==='Mesa'?v.tableAccount:'',booking:mode==='Estadía'||destination==='Estadía'?v.booking:'',mode:['Cortesía','Interno'].includes(destination)?'Sin cobro':mode}:form==='beverageAccount'?v:form==='beverageSettle'?{...v,tableAccount:selected}:{...v,dispatch:selected})}>
  {form==='beverageAccount'&&<><Field label="Mesa / identificador físico" name="table"/><Field label="Hora del hotel" name="time" type="time" value="12:00"/><p className="form-note">Cada apertura crea una cuenta independiente, aunque la mesa se reutilice.</p></>}
  {form==='beverageDispatch'&&<><Field label="Hora del despacho (Buenos Aires)" name="time" type="time" value={new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())}/><Choice label="Bebida" name="product" value={product} onChange={setProduct} options={data.products.filter(p=>p.category==='Bebidas').map(p=>[p.id,p.name])}/><Field label="Cantidad en unidad del producto" name="qty" type="number" min="0.001" step="0.001" value="1"/><Choice label="Destino físico" name="destination" value={destination} onChange={v=>{setDestination(v);setMode(v==='Mesa'?'Pendiente':'Inmediato');}} options={['Mesa','Estadía','Cortesía','Interno']}/>{destination==='Mesa'&&<Choice label="Cuenta de mesa abierta" name="tableAccount" options={open.map(a=>[a.id,`${a.table_name} · ${a.id.slice(0,8)}`])}/>}{!['Cortesía','Interno'].includes(destination)&&<Choice label="Condición de cobro" name="mode" value={mode} onChange={setMode} options={destination==='Mesa'?['Pendiente','Inmediato','Estadía']:['Inmediato','Estadía']}/>}{(destination==='Estadía'||mode==='Estadía')&&<Choice label="Estadía para identificar / cargar" name="booking" options={bookings.map(b=>[b.id,`Hab. ${b.room} · ${b.guest}`])}/>}<Field label="Cliente / referencia" name="customer" value="Cliente de restaurante"/><Field key={product} label="Precio aplicado por unidad (ARS)" name="price" readOnly={!!identity&&!can(identity,'restaurant.price')} type="number" min="0" step="0.01" value={(data.products.find(p=>p.id===product)?.price??0)/100}/><Choice label="Cuenta para cobro inmediato" name="account" options={accounts}/><Field label="Motivo de cortesía / interno" name="reason" required={['Cortesía','Interno'].includes(destination)}/><p className="form-note">El despacho descuenta stock una vez. Cobrar o transferir después no lo descuenta de nuevo.</p></>}
  {form==='beverageSettle'&&<><p className="form-note">Cuenta {data.beverage_accounts.find(a=>a.id===selected)?.table_name} · {selected.slice(0,8)} · pendiente {currency(tableTotal(data,selected))}</p><Choice label="Cerrar mediante" name="method" options={['Cobro','Estadía']}/><Choice label="Cuenta para el cobro" name="account" options={accounts}/><Choice label="Estadía (para transferir cargos)" name="booking" options={[['','Sin estadía'],...bookings.map(b=>[b.id,`Hab. ${b.room} · ${b.guest}`] as [string,string])]}/></>}
  {(form==='beverageReturn'||form==='beverageCorrect')&&<><p className="form-note">{target?.label} · {target?.qty} despachadas · {returned(selected)} devueltas. La corrección económica no devuelve stock. Los cobros y días cerrados requieren un circuito de regularización pendiente.</p>{form==='beverageReturn'&&<><Field label="Cantidad que regresó en condiciones de venta" name="qty" type="number" min="0.001" step="0.001"/><p className="form-note">Confirmá el regreso físico. Esta operación no devuelve dinero ni anula cargos.</p></>}<Field label="Motivo" name="reason"/></>}
 </Editor>}
 <Table headers={['Mesa / cuenta','Apertura','Pendiente','Estado','Acción']} rows={data.beverage_accounts.slice().sort((a,b)=>b.opened_at.localeCompare(a.opened_at)).map(a=>{const s=data.beverage_settlements.find(s=>s.table_account===a.id);return [<span key="id">{a.table_name}<small>Cuenta {a.id.slice(0,8)}</small></span>,new Date(a.opened_at).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'}),currency(s?0:tableTotal(data,a.id)),s?`Cerrada · ${s.method}`:'Abierta',!s&&<Button variant="outline" onClick={()=>begin('beverageSettle',a.id)} permission="restaurant.edit" anyPermission={['restaurant.collect','restaurant.charge']}>Cobrar / transferir</Button>];})}/>
 <h3 className="supply-subheading">Despachos del {date}</h3><Table headers={['Hora / destino','Bebida','Cantidad / devolución','Precio / total','Cobro','Responsable / observación','Acciones']} rows={data.beverage_dispatches.filter(d=>data.sales.find(s=>s.id===d.sale)?.date===date).map(d=>{const s=data.sales.find(s=>s.id===d.sale)!;return [<span key="dest">{d.time} · {d.destination}<small>{data.beverage_accounts.find(a=>a.id===d.table_account)?.table_name??s.customer} {d.table_account?.slice(0,8)}</small></span>,s.label,`${s.qty} / devueltas ${returned(s.id)}`,<span key="money">{currency(d.price)} / {currency(s.amount)}</span>,dispatchStatus(data,s.id),<span key="who">{d.responsible}<small>{d.reason} {d.observation}</small></span>,<div key="actions" className="meal-row-actions">{returned(s.id)<s.qty&&<Button variant="outline" onClick={()=>begin('beverageReturn',s.id)} permission="restaurant.edit">Devolución física</Button>}{!data.beverage_corrections.some(c=>c.dispatch===s.id)&&<Button variant="outline" onClick={()=>begin('beverageCorrect',s.id)} permission="restaurant.cancel">Corregir</Button>}</div>];})}/>
 <History data={data} actions={['beverageAccount','beverageDispatch','beverageSettle','beverageReturn','beverageCorrect']}/></section>;
}
