'use client';

import { MenuDailySummary } from '@/components/hotel-planning';
import { Input } from '@/components/ui/input';
import { departureText,kitchenRows,kitchenTotals,services,type KitchenRow,type Service } from '@/lib/hotel-meals';
import type { Booking,HotelData } from '@/lib/hotel-types';
import { serializeCsv } from '@/lib/hotel-view';
import { ActionButton as Button } from '@/modules/access/context';
import { useState,type FormEvent } from 'react';
type Save=(action:string,data:unknown)=>Promise<void>;
type Edit={action:string;guest?:string;booking?:string;date?:string;service?:Service;plan?:string;version?:number;active?:boolean};
function MealEditor({edit,data,date,onSave,onClose}:{edit:Edit;data:HotelData;date:string;onSave:Save;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[booking,setBooking]=useState(edit.booking??data.bookings.find(b=>['Confirmada','Alojado'].includes(b.status))?.id??'');
 const guests=data.booking_guests.filter(g=>g.booking===booking&&g.position<=(data.bookings.find(b=>b.id===booking)?.pax??0));
 const guest=data.booking_guests.find(g=>g.id===edit.guest);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),values:Record<string,unknown>=Object.fromEntries(f);if(edit.action==='mealSuspend')values.active=edit.active??true;if(['mealSuspend','mealServe'].includes(edit.action))values.guests=f.getAll('guests');setBusy(true);setError('');try{await onSave(edit.action,values);onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 const input=(label:string,name:string,value='',type='text',required=true)=><label className="field"><span>{label}</span><Input className="control" name={name} defaultValue={value} type={type} required={required}/></label>;
 return <section className="panel spaced meal-editor"><h3>{({guestProfile:'Datos de alimentación por persona',mealSuspend:edit.active===false?'Reactivar comidas':'Suspender comidas',mealServe:'Confirmar servicio realizado',mealPlan:'Agregar previsión explícita',mealPlanStatus:'Actualizar asistencia',meal:'Elección de MP para un día'} as Record<string,string>)[edit.action]}</h3><form className="entry-form" onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">
 {edit.action==='guestProfile'?<><input type="hidden" name="guest" value={guest?.id??''}/><input type="hidden" name="version" value={guest?.version??0}/>{input('Nombre de esta persona','name',guest?.name,'text',false)}{input('Restricciones (texto indicado)','restrictions',guest?.restrictions,'text',false)}{input('Preferencias (sin cambiar régimen ni precio)','preferences',guest?.preferences,'text',false)}</>:null}
 {['mealSuspend','mealServe','meal'].includes(edit.action)&&<><label className="field"><span>Reserva</span><select className="control" name="booking" value={booking} onChange={e=>setBooking(e.target.value)}>{data.bookings.filter(b=>['Confirmada','Alojado'].includes(b.status)).map(b=><option key={b.id} value={b.id}>{b.guest} · Hab. {b.room}</option>)}</select></label>{edit.action!=='meal'&&<label className="field"><span>Personas afectadas (seleccioná todas para toda la reserva)</span><select className="control" key={booking} name="guests" multiple required defaultValue={edit.guest?[edit.guest]:guests.map(g=>g.id)}>{guests.map(g=><option key={g.id} value={g.id}>{g.name||`Persona ${g.position}`}</option>)}</select></label>}</>}
 {edit.action==='mealSuspend'?<>{input('Desde (incluido)','start',edit.date??date,'date')}{input('Hasta (incluido)','end',edit.date??date,'date')}{input('Motivo','reason')}</>:['mealServe','mealPlan','meal'].includes(edit.action)?input('Fecha','date',edit.date??date,'date'):null}
 {['mealSuspend','mealServe','mealPlan'].includes(edit.action)&&<label className="field"><span>Servicio</span><select className="control" name="service" defaultValue={edit.service??'Cena'}>{services.map(s=><option key={s}>{s}</option>)}</select></label>}
 {edit.action==='meal'&&<label className="field"><span>MP del día</span><select className="control" name="meal" defaultValue={data.meal_overrides.find(m=>m.booking===booking&&m.date===(edit.date??date))?.meal??data.bookings.find(b=>b.id===booking)?.meal??'Cena'}><option>Cena</option><option>Almuerzo</option></select></label>}
 {edit.action==='mealPlan'&&<><label className="field"><span>Persona o cliente externo</span><select className="control" name="guest" defaultValue={edit.guest??''}><option value="">Cliente externo</option>{data.booking_guests.filter(g=>data.bookings.some(b=>b.id===g.booking&&g.position<=b.pax&&['Confirmada','Alojado'].includes(b.status))).map(g=><option key={g.id} value={g.id}>{g.name||`Hab. ${data.bookings.find(b=>b.id===g.booking)?.room} · Persona ${g.position}`}</option>)}</select></label>{input('Nombre del cliente / grupo','customer',guest?.name||'')}{input('Personas (para un huésped: 1)','qty','1','number')}<p className="full-width muted">Registrar previsión o asistencia no registra cobros. Los consumos adicionales y su precio se cargan por separado. En el día de salida esta previsión confirma expresamente un servicio fuera del régimen incluido actual.</p></>}
 {edit.action==='mealPlanStatus'&&<><input type="hidden" name="id" value={edit.plan}/><input type="hidden" name="version" value={edit.version??0}/><label className="field"><span>Estado</span><select className="control" name="status"><option>Servido</option><option>Cancelada</option></select></label></>}
 {input('Responsable declarado','responsible')}{input('Observación','observation',edit.action==='guestProfile'?guest?.observation:'','text',false)}
 </div>{error&&<p role="alert" className="negative">{error}</p>}<div className="form-actions"><Button type="button" variant="outline" onClick={onClose}>Volver</Button><Button disabled={busy} type="submit">{busy?'Guardando…':'Guardar'}</Button></div></fieldset></form></section>;
}
function MealHistory({data,booking}:{data:HotelData;booking?:string}){
 const logs=data.audit_log.filter(a=>['guestProfile','mealSuspend','mealServe','mealPlan','mealPlanStatus','meal'].includes(a.action)).filter(a=>{if(!booking)return true;try{const parsed=JSON.parse(a.detail),d=parsed.input??parsed;return d.booking===booking||data.booking_guests.some(g=>g.booking===booking&&g.id===d.guest)||data.meal_plans.some(p=>p.id===d.id&&data.booking_guests.some(g=>g.booking===booking&&g.id===p.guest));}catch{return false;}}).sort((a,b)=>b.created.localeCompare(a.created));
 return <details className="meal-history history"><summary>Historial de alimentación y asistencia ({logs.length})</summary>{logs.map(a=>{let d:Record<string,unknown>={};try{const p=JSON.parse(a.detail);d=p.input??p;}catch{}return <p className="history-record" key={a.id}><b>{new Date(a.created).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'})} · {String(d.responsible??a.actor)}</b><br/>{({guestProfile:'Datos por persona',mealSuspend:'Suspensión / reactivación',mealServe:'Servicio incluido realizado',mealPlan:'Previsión explícita',mealPlanStatus:'Estado de asistencia',meal:'Elección de MP'} as Record<string,string>)[a.action]} · {String(d.date??d.start??'')} {String(d.service??d.meal??'')} · {String(d.reason??'')} {String(d.observation??'')}<br/><small>{String(d.name??'')} {d.restrictions!==undefined&&` · Restricciones: ${String(d.restrictions)||'Sin registrar'}`} {d.preferences!==undefined&&` · Preferencias: ${String(d.preferences)||'Sin registrar'}`} {d.end!==undefined&&` · Hasta: ${String(d.end)}`} {d.active!==undefined&&(d.active?' · Suspensión':' · Reactivación')} {d.status!==undefined&&` · Estado: ${String(d.status)}`} {Array.isArray(d.guests)&&` · Personas: ${d.guests.map(id=>{const g=data.booking_guests.find(g=>g.id===id);return g?.name||'Persona '+g?.position;}).join(', ')}`} {d.customer!==undefined&&` · Cliente: ${String(d.customer)} · Personas: ${String(d.qty??'')}`}</small></p>})}</details>;
}
export function GuestMeals({booking,data,date,onSave}:{booking:Booking;data:HotelData;date:string;onSave:Save}){
 const [edit,setEdit]=useState<Edit|null>(null),closed=['Cancelada','Finalizada'].includes(booking.status);
 return <section className="reservation-section"><h3>Alimentación · {booking.regime==='MP'?'Media pensión':booking.regime==='PC'?'Pensión completa':'Desayuno'}</h3><p>Regla actual: llegada incluida y salida excluida. {booking.regime==='MP'&&<>MP inicial: {booking.meal}; elección del {date}: {data.meal_overrides.find(m=>m.booking===booking.id&&m.date===date)?.meal??booking.meal}. No cambia el precio.</>}</p>{data.booking_guests.filter(g=>g.booking===booking.id&&g.position<=booking.pax).map(g=><div className="guest-meal" key={g.id}><b>{g.name||`Persona ${g.position} · nombre pendiente`}</b><p>Restricciones: {g.restrictions||'Sin registrar'}</p><p>Preferencias: {g.preferences||'Sin registrar'}</p><p>Observaciones: {g.observation||'Sin observaciones'}</p><Button variant="outline" disabled={closed} onClick={()=>setEdit({action:'guestProfile',guest:g.id})} permission="meals.edit">Editar esta persona</Button></div>)}<p className="muted">Se conserva el texto declarado. La app no determina qué alimentos son aptos.</p><div className="inline-controls"><Button variant="outline" disabled={closed} onClick={()=>setEdit({action:'mealSuspend',booking:booking.id})} permission="meals.edit">Suspender comidas</Button>{booking.regime==='MP'&&<Button variant="outline" disabled={closed} onClick={()=>setEdit({action:'meal',booking:booking.id,date})} permission="meals.edit">Cambiar MP del día</Button>}</div>{data.meal_suspensions.filter(s=>s.active&&data.booking_guests.some(g=>g.id===s.guest&&g.booking===booking.id)).map(s=><p key={s.guest+s.date+s.service}>{s.date} · {s.service} · {data.booking_guests.find(g=>g.id===s.guest)?.name||`Persona ${data.booking_guests.find(g=>g.id===s.guest)?.position}`} · Suspendida: {s.reason} <Button variant="outline" disabled={closed} onClick={()=>setEdit({action:'mealSuspend',booking:booking.id,guest:s.guest,date:s.date,service:s.service as Service,active:false})} permission="meals.edit">Reactivar</Button></p>)}{edit&&<MealEditor key={[edit.action,edit.guest,edit.booking,edit.date,edit.service,edit.plan,edit.active].join(':')} edit={edit} data={data} date={date} onSave={onSave} onClose={()=>setEdit(null)}/>}<MealHistory data={data} booking={booking.id}/></section>;
}
export function Kitchen({data,date,onSave}:{data:HotelData;date:string;onSave:Save}){
 const [service,setService]=useState<Service>('Cena'),[edit,setEdit]=useState<Edit|null>(null);
 const rows=kitchenRows(data,date,service),totals=kitchenTotals(rows);
 function exportList(){const text=serializeCsv([['Fecha','Servicio','Habitación','Huésped','Personas previstas','Régimen','Carácter','Restricciones','Preferencias','Observaciones','Suspensión / motivo','Estado'],...rows.map(r=>[date,service,r.room,r.name,r.expected,r.regime,r.character,r.restrictions,r.preferences,r.observation,r.reason,r.state])]);const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`cocina-${date}-${service}.csv`;a.click();URL.revokeObjectURL(url);}
 function action(r:KitchenRow){if(r.state==='Suspendida')setEdit({action:'mealSuspend',booking:r.booking!,guest:r.guest!,date,service,active:false});else if(r.plan)setEdit({action:'mealPlanStatus',plan:r.plan,version:r.version});else if(r.character==='Incluida')setEdit({action:'mealServe',booking:r.booking!,guest:r.guest!,date,service});else setEdit({action:'mealPlan',guest:r.guest!,date,service});}
 return <section className="panel kitchen-list"><div className="panel-heading"><h2>Cocina y recepción · {date}</h2><div className="inline-controls"><select className="control" aria-label="Servicio de cocina" value={service} onChange={e=>setService(e.target.value as Service)}>{services.map(s=><option key={s}>{s}</option>)}</select><Button variant="outline" onClick={exportList} permission="meals.export">Exportar listado CSV</Button><Button onClick={()=>setEdit({action:'mealPlan',date,service})} permission="meals.create">Agregar previsión</Button><Button variant="outline" onClick={()=>setEdit({action:'mealSuspend',date,service})} permission="meals.edit">Suspender comidas</Button></div></div><p>Regla vigente: comidas incluidas desde llegada hasta el día anterior a salida. Los servicios de salida se muestran pendientes de revisión y requieren previsión explícita. Cada fila de huésped es una persona.</p><MenuDailySummary data={data} date={date} service={service}/><div className="meal-summary">{[['Huéspedes',totals.hotel],['Clientes externos',totals.external],['Total general',totals.total]].map(([label,n])=><div key={label} className="panel"><span>{label}</span><strong>{n}</strong><small>personas previstas · incluye las ya servidas</small></div>)}</div><div className="table-wrap"><table className="kitchen-table"><thead><tr>{['Hab. / persona','Previstas','Régimen / carácter','Restricciones y preferencias','Observaciones / suspensión','Estado',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{r.room} · {r.name}</td><td>{r.expected}</td><td>{r.regime} · {r.character}</td><td>Restricciones: {r.restrictions||'Sin registrar'}<br/>Preferencias: {r.preferences||'Sin registrar'}</td><td>{r.observation}<br/>{r.reason&&`Suspendida: ${r.reason}`}</td><td>{r.state}</td><td><div className="meal-row-actions">{r.state!=='Servido'&&!r.state.startsWith('Servicio histórico')&&<Button variant="outline" onClick={()=>action(r)} permission="meals.edit">{r.state==='Suspendida'?'Reactivar':r.plan?'Actualizar':r.character==='Incluida'?'Registrar servicio':'Confirmar adicional'}</Button>}{r.booking&&data.bookings.find(b=>b.id===r.booking)?.regime==='MP'&&<Button variant="outline" onClick={()=>setEdit({action:'meal',booking:r.booking!,date})} permission="meals.edit">MP del día</Button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={7}>Sin previsiones para este servicio.</td></tr>}</tbody></table></div><p className="muted">Las suspensiones no cambian importes. Previsión y servicio son registros separados: nadie se marca servido automáticamente. Los clientes externos sólo se suman por estas previsiones explícitas.</p>{edit&&<MealEditor key={[edit.action,edit.guest,edit.booking,edit.date,edit.service,edit.plan,edit.active].join(':')} edit={edit} data={data} date={date} onSave={onSave} onClose={()=>setEdit(null)}/>}<MealHistory data={data}/></section>;
}
export function Departures({data,date,onSelect}:{data:HotelData;date:string;onSelect:(id:string)=>void}){
 return <section className="panel spaced"><div className="panel-heading"><h2>Próximas salidas · fecha de consulta {date}</h2></div>{data.bookings.filter(b=>!['Cancelada','Finalizada'].includes(b.status)).sort((a,b)=>a.end.localeCompare(b.end)||a.room-b.room).map(b=><button className="departure-row text-link" key={b.id} onClick={()=>onSelect(b.id)}>{b.end} · Hab. {b.room} · {b.guest} · <b>{departureText(b,date)}</b></button>)}</section>;
}
